// build.js - Concatenates all lib modules + content.js into a single bundled file.
// Chrome content scripts don't support `type: module`, so we bundle inline.
// Also generates popup-bundle.js — same lib modules wrapped as a global object
// (`window.WG_POPUP_LIB`) so the extension popup page can use them without
// duplicating logic.

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const ROOT = __dirname;
const LIB = path.join(ROOT, "lib");
const OUT = path.join(ROOT, "content.js");
const OUT_POPUP = path.join(ROOT, "popup-bundle.js");

const ORDER = [
  "constants.js",
  "decoder.js",
  "typosquatting.js",
  "multicall-decoder.js",
  "universal-router.js",
  "risk-engine.js",
  "capabilities.js",
  "simulator.js",
  "mev-detector.js",
  "revoke-generator.js",
  "eip7702-detector.js",
  "session-key-analyzer.js",
  "threat-feed.js",
  "wallet-dna.js",
  "drainer-detector.js",
  "visual-phish.js",
  "hw-wallet.js",
  "safe-multisig.js",
  "explain.js"
];

// Popup bundle gets all the modules PLUS the i18n system AND popup-only
// features (address book for labels).
// Content scripts don't show UI, so they don't need i18n or address book.
const POPUP_ORDER = [...ORDER, "address-book.js", "i18n.js"];

// We need a single IIFE so internal `const` declarations don't collide.
// Strategy: read each lib file, strip its `import` statements and `export` keywords,
// then wrap each module body in an IIFE that returns its exports on a per-module object.

function stripModuleSyntax(src) {
  // Remove top-level imports.
  src = src.replace(/^\s*import\s+\{[^}]*\}\s+from\s+["'][^"']+["'];?\s*$/gm, "");
  src = src.replace(/^\s*import\s+\*\s+as\s+\w+\s+from\s+["'][^"']+["'];?\s*$/gm, "");
  src = src.replace(/^\s*import\s+["'][^"']+["'];?\s*$/gm, "");

  // Collect exports.
  const exports = [];
  const exportRegex = /^export\s+(?:async\s+)?function\s+(\w+)/gm;
  let m;
  while ((m = exportRegex.exec(src))) {
    exports.push(m[1]);
  }
  // Also handle `export const NAME`.
  const exportConstRegex = /^export\s+const\s+(\w+)/gm;
  while ((m = exportConstRegex.exec(src))) {
    exports.push(m[1]);
  }

  // Strip the `export` keyword from those declarations.
  src = src.replace(/^export\s+(async\s+function\s+\w+)/gm, "$1");
  src = src.replace(/^export\s+(function\s+\w+)/gm, "$1");
  src = src.replace(/^export\s+(const\s+\w+)/gm, "$1");

  return { src, exports };
}

function buildModule(name, raw) {
  const { src, exports } = stripModuleSyntax(raw);
  const exportList = exports.join(", ");
  return `
/* ============================================================
 * lib/${name}
 * ============================================================ */
const ${name.replace(/\W/g, "_")}_exports = (function() {
${src}
return { ${exportList} };
})();
`;
}

function buildBindings(modules) {
  // Generate alias consts so the content.js orchestrator can reference
  // them by their original names.
  let out = "";
  for (const { name, exports } of modules) {
    const ns = `${name.replace(/\W/g, "_")}_exports`;
    for (const e of exports) {
      out += `const ${e} = ${ns}.${e};\n`;
    }
  }
  return out;
}

// Read lib files in order.
const modules = [];
for (const file of ORDER) {
  const filePath = path.join(LIB, file);
  const raw = fs.readFileSync(filePath, "utf8");
  const { exports } = stripModuleSyntax(raw);
  modules.push({ name: file, exports, raw });
}

// Read content.js orchestrator. Support two states:
//   (a) Source form (has ES imports + raw orchestrator code)
//   (b) Bundled form (starts with "// content.js - BUNDLED BUILD")
// In case (b), extract only the orchestrator portion (after the marker comment).
const orchestratorPath = path.join(ROOT, "content.js");
let orchestrator = fs.readFileSync(orchestratorPath, "utf8");

if (orchestrator.includes("// content.js - BUNDLED BUILD")) {
  // Bundled form: keep only the part after the "ORCHESTRATOR" marker.
  const marker = "// ============================================================\n// ORCHESTRATOR (was content.js)\n// ============================================================";
  const idx = orchestrator.indexOf(marker);
  if (idx >= 0) {
    orchestrator = orchestrator.slice(idx + marker.length);
  }
} else {
  // Source form: strip import statements at the top.
  orchestrator = orchestrator.replace(/^\s*import\s+\{[^}]*\}\s+from\s+["'][^"']+["'];?\s*$/gm, "");
  orchestrator = orchestrator.replace(/^\s*import\s+\*\s+as\s+\w+\s+from\s+["'][^"']+["'];?\s*$/gm, "");
}

// Build the bundle.
const bundle = `// content.js - BUNDLED BUILD (generated by build.js)
// Auto-generated. To regenerate: node build.js
// All lib modules are inlined as IIFEs and aliased to their original names.
${modules.map((m) => buildModule(m.name, m.raw)).join("\n")}

// ============================================================
// BINDINGS - alias exports to their original names
// ============================================================
${buildBindings(modules)}

// ============================================================
// ORCHESTRATOR (was content.js)
// ============================================================
${orchestrator}
`;

fs.writeFileSync(OUT, bundle, "utf8");
console.log(`Bundled: ${OUT} (${bundle.length} bytes)`);

// ---- popup-bundle.js ----
//
// Same lib modules, but packaged as a global `window.WG_POPUP_LIB` object so
// the popup page (which is an isolated extension page that can't `import`
// from lib/*) can access them. Excludes the content.js orchestrator (which
// is content-script-only and uses chrome.runtime APIs the popup doesn't need).
//
// Each lib file's exports are namespaced under its module filename
// (without .js): `WG_POPUP_LIB.constants`, `WG_POPUP_LIB.decoder`, etc.
// So `revoke-generator.js` exports land under `WG_POPUP_LIB.revokeGenerator`
// (dash → camelCase).

function popupBundle(modules) {
  const namespaces = {};
  let inner = "";
  for (const { name, raw } of modules) {
    const { src, exports } = stripModuleSyntax(raw);
    const ns = toCamelCase(name.replace(/\.js$/, ""));
    namespaces[name] = ns;
    inner += `
    // ============================================================
    // ${name}
    // ============================================================
    "${ns}": (function() {
${src}
return { ${exports.join(", ")} };
    })(),`;
  }

  // Inline locale tables as window.__WG_LOCALES__ for the i18n module.
  const localesDir = path.join(LIB, "locales");
  let localesBlock = "";
  let localesObject = {};
  if (fs.existsSync(localesDir)) {
    const localeFiles = fs.readdirSync(localesDir).filter((f) => f.endsWith(".js")).sort();
    for (const file of localeFiles) {
      const code = file.replace(/\.js$/, "");
      const raw = fs.readFileSync(path.join(localesDir, file), "utf8");
      // Extract the MESSAGES object literal.
      const m = raw.match(/export\s+const\s+MESSAGES\s*=\s*(\{[\s\S]*?\});?\s*$/);
      if (m) {
        localesObject[code] = m[1];
      }
    }
    if (Object.keys(localesObject).length > 0) {
      localesBlock = `
  // ============================================================
  // Locales (injected into window.__WG_LOCALES__ for i18n module)
  // ============================================================
  global.__WG_LOCALES__ = { ${Object.entries(localesObject).map(([k, v]) => `"${k}": ${v}`).join(",\n    ")} };
`;
    }
  }

  return `// popup-bundle.js - BUNDLED BUILD (generated by build.js)
// Auto-generated. To regenerate: node build.js
// Exposes all lib modules as \`window.WG_POPUP_LIB.<moduleName>\`.
// Camel-case: revoke-generator.js → WG_POPUP_LIB.revokeGenerator.
(function (global) {
  "use strict";
${localesBlock}
  var mods = {${inner}
  };
  global.WG_POPUP_LIB = { ${Object.entries(namespaces).map(([k, v]) => `"${v}": mods.${v}`).join(", ")} };
})(typeof window !== "undefined" ? window : globalThis);
`;
}

function toCamelCase(s) {
  return s.replace(/-([a-z])/g, (_, c) => c.toUpperCase()).replace(/^\./, "");
}

// Read popup-specific modules (includes i18n, which content.js doesn't need).
const popupModules = [];
for (const file of POPUP_ORDER) {
  const filePath = path.join(LIB, file);
  const raw = fs.readFileSync(filePath, "utf8");
  const { exports } = stripModuleSyntax(raw);
  popupModules.push({ name: file, exports, raw });
}

const popupSrc = popupBundle(popupModules);
fs.writeFileSync(OUT_POPUP, popupSrc, "utf8");
console.log(`Bundled: ${OUT_POPUP} (${popupSrc.length} bytes)`);
