// build.js - Concatenates all lib modules + content.js into a single bundled file.
// Chrome content scripts don't support `type: module`, so we bundle inline.

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const ROOT = __dirname;
const LIB = path.join(ROOT, "lib");
const OUT = path.join(ROOT, "content.js");

const ORDER = [
  "constants.js",
  "decoder.js",
  "typosquatting.js",
  "multicall-decoder.js",
  "universal-router.js",
  "risk-engine.js",
  "capabilities.js",
  "simulator.js"
];

// We need a single IIFE so internal `const` declarations don't collide.
// Strategy: read each lib file, strip its `import` statements and `export` keywords,
// then wrap each module body in an IIFE that returns its exports on a per-module object.

function stripModuleSyntax(src) {
  // Remove top-level imports.
  src = src.replace(/^\s*import\s+\{[^}]*\}\s+from\s+["'][^"']+["'];?\s*$/gm, "");
  src = src.replace(/^\s*import\s+\*\s+as\s+\w+\s+from\s+["'][^"']+["'];?\s*$/gm, "");
  src = src.replace(/^\s*import\s+["'][^"']+["'];?\s*$/gm, "");

  // Collect exports.
  const exports = [];
  const exportRegex = /^export\s+(?:async\s+)?function\s+(\w+)/gm;
  let m;
  while ((m = exportRegex.exec(src))) {
    exports.push(m[1]);
  }
  // Also handle `export const NAME`.
  const exportConstRegex = /^export\s+const\s+(\w+)/gm;
  while ((m = exportConstRegex.exec(src))) {
    exports.push(m[1]);
  }

  // Strip the `export` keyword from those declarations.
  src = src.replace(/^export\s+(async\s+function\s+\w+)/gm, "$1");
  src = src.replace(/^export\s+(function\s+\w+)/gm, "$1");
  src = src.replace(/^export\s+(const\s+\w+)/gm, "$1");

  return { src, exports };
}

function buildModule(name, raw) {
  const { src, exports } = stripModuleSyntax(raw);
  const exportList = exports.join(", ");
  return `
/* ============================================================
 * lib/${name}
 * ============================================================ */
const ${name.replace(/\W/g, "_")}_exports = (function() {
${src}
return { ${exportList} };
})();
`;
}

function buildBindings(modules) {
  // Generate alias consts so the content.js orchestrator can reference
  // them by their original names.
  let out = "";
  for (const { name, exports } of modules) {
    const ns = `${name.replace(/\W/g, "_")}_exports`;
    for (const e of exports) {
      out += `const ${e} = ${ns}.${e};\n`;
    }
  }
  return out;
}

// Read lib files in order.
const modules = [];
for (const file of ORDER) {
  const filePath = path.join(LIB, file);
  const raw = fs.readFileSync(filePath, "utf8");
  const { exports } = stripModuleSyntax(raw);
  modules.push({ name: file, exports, raw });
}

// Read content.js orchestrator. Support two states:
//   (a) Source form (has ES imports + raw orchestrator code)
//   (b) Bundled form (starts with "// content.js - BUNDLED BUILD")
// In case (b), extract only the orchestrator portion (after the marker comment).
const orchestratorPath = path.join(ROOT, "content.js");
let orchestrator = fs.readFileSync(orchestratorPath, "utf8");

if (orchestrator.includes("// content.js - BUNDLED BUILD")) {
  // Bundled form: keep only the part after the "ORCHESTRATOR" marker.
  const marker = "// ============================================================\n// ORCHESTRATOR (was content.js)\n// ============================================================";
  const idx = orchestrator.indexOf(marker);
  if (idx >= 0) {
    orchestrator = orchestrator.slice(idx + marker.length);
  }
} else {
  // Source form: strip import statements at the top.
  orchestrator = orchestrator.replace(/^\s*import\s+\{[^}]*\}\s+from\s+["'][^"']+["'];?\s*$/gm, "");
  orchestrator = orchestrator.replace(/^\s*import\s+\*\s+as\s+\w+\s+from\s+["'][^"']+["'];?\s*$/gm, "");
}

// Build the bundle.
const bundle = `// content.js - BUNDLED BUILD (generated by build.js)
// Auto-generated. To regenerate: node build.js
// All lib modules are inlined as IIFEs and aliased to their original names.
${modules.map((m) => buildModule(m.name, m.raw)).join("\n")}

// ============================================================
// BINDINGS - alias exports to their original names
// ============================================================
${buildBindings(modules)}

// ============================================================
// ORCHESTRATOR (was content.js)
// ============================================================
${orchestrator}
`;

fs.writeFileSync(OUT, bundle, "utf8");
console.log(`Bundled: ${OUT} (${bundle.length} bytes)`);
