// content.js - BUNDLED BUILD (generated by build.js)
// Auto-generated. To regenerate: node build.js
// All lib modules are inlined as IIFEs and aliased to their original names.

/* ============================================================
 * lib/constants.js
 * ============================================================ */
const constants_js_exports = (function() {
// lib/constants.js - Shared constants used across modules.

// Known trusted domains (lowercased, no leading www.).
//
// The list is intentionally curated rather than exhaustive: each entry
// must be a stable, well-known Web3 entrypoint that users actually
// visit. False positives (flagging a legitimate new protocol as a
// typosquat of "uniswap.org") erode trust in the feature, so we
// keep the list conservative. To add a domain:
//   1. Verify it's a public-good protocol (not a random DeFi clone).
//   2. Add the registrable domain (e.g. `uniswap.org`, not `app.uniswap.org`).
//   3. Bump the count in README.md + CHANGELOG.md + THREAT_MODEL.md.
//   4. Add a regression test in test-typosquat.js that the new entry is
//      correctly classified as `trusted`.
const TRUSTED_DOMAINS = [
  // ---- DEX & AMM (existing) ----
  "uniswap.org", "app.uniswap.org",
  "pancakeswap.finance",
  "curve.fi", "balancer.fi", "sushi.com",
  "1inch.io", "matcha.xyz", "cow.fi",

  // ---- Lending & yield (existing + new) ----
  "aave.com", "compound.finance",
  "lido.fi", "rocketpool.net",
  "makerdao.com", "spark.fi",
  "morpho.org", "convex.fi", "yearn.fi",
  "beefy.com", "frax.finance", "pendle.finance",

  // ---- NFTs ----
  "opensea.io", "looksrare.org",
  "blur.io", "magiceden.io",
  "foundation.app", "zora.co", "sudoswap.xyz",

  // ---- Cross-chain bridges & messaging ----
  "stargate.finance", "across.to", "hop.exchange",
  "layerzero.network", "wormhole.com",

  // ---- Wallets ----
  "metamask.io", "rabby.io", "frame.xyz", "rainbow.me", "zerion.io",

  // ---- Explorers ----
  "etherscan.io", "polygonscan.com", "arbiscan.io",

  // ---- Perpetuals / derivatives ----
  "gmx.io", "dydx.exchange", "hyperliquid.xyz",

  // ---- Identity & social ----
  "ens.domains", "mirror.xyz", "lens.xyz"
];

// Hardcoded seed blacklist of known drainers / phishers.
const SEED_BLACKLIST = [
  "0x71C7656EC7ab88b098defB751B7401B5f6d14731",
  "0x281055afc982d96fab65b3a49cac8b878184cb16",
  "HN7c7ZES4CfX6NLF3gqas9mE28tBg7cZ4j5Xv7gK7FAE"
];

// Well-known safe contracts that get a trust bonus.
const KNOWN_SAFE_CONTRACTS = new Set([
  "0x7a250d5630b4cf539739df2c5dacb4c659f2488d", // Uniswap V2 Router
  "0x68b3465833fb72a70ecdf485e0e4c7bd8665fc45", // Uniswap V3 Router 2
  "0xef1c6e67703c7bd71d701e3008ed740d79d164b0", // Uniswap Universal Router 2
  "0x000000000022d473030f116ddee9f6b43ac78ba3", // Permit2
  "0x1111111254eeb25477b68fb85ed929f73a960582", // 1inch v5 Router
  "0xba12222222228d8ba445958a75a0704d566bf2c8", // Balancer Vault
  "0x68b3465833fb72a70ecdf485e0e4c7bd8665fc45"  // Uniswap V3 SwapRouter02
]);

// Universal Router 2 command opcodes (single-byte).
// Reference: https://docs.uniswap.org/contracts/universal-router/technical-reference
const UR_COMMANDS = {
  0x00: { name: "V3_SWAP_EXACT_IN",       risk: "MEDIUM",  desc: "Swap exact amount of tokenA for tokenB through a V3 pool." },
  0x01: { name: "V3_SWAP_EXACT_OUT",      risk: "MEDIUM",  desc: "Receive exact amount of tokenB by spending variable tokenA through a V3 pool." },
  0x02: { name: "PERMIT2_TRANSFER_FROM",  risk: "HIGH",    desc: "Pulls tokens via a Permit2 allowance. Requires prior Permit2 signature." },
  0x03: { name: "PERMIT2_PERMIT",         risk: "CRITICAL", desc: "Submits a Permit2 batch permit signature for token spending." },
  0x04: { name: "SWEEP",                  risk: "LOW",     desc: "Transfers leftover tokens to a recipient (usually the user)." },
  0x05: { name: "TRANSFER",               risk: "LOW",     desc: "Direct ERC-20 transfer to a recipient." },
  0x06: { name: "PAY_PORTION",            risk: "LOW",     desc: "Sends a portion of the swapped tokens to a payee (fee/partner split)." },
  0x07: { name: "V2_SWAP_EXACT_IN",       risk: "MEDIUM",  desc: "Swap exact amount of tokenA for tokenB through a V2 pair." },
  0x08: { name: "V2_SWAP_EXACT_OUT",      risk: "MEDIUM",  desc: "Receive exact tokenB by spending variable tokenA through a V2 pair." },
  0x09: { name: "PERMIT",                 risk: "CRITICAL", desc: "Legacy Permit signature for token allowance." },
  0x0a: { name: "WRAP_ETH",               risk: "LOW",     desc: "Wraps native ETH into WETH." },
  0x0b: { name: "UNWRAP_WETH",            risk: "LOW",     desc: "Unwraps WETH back into native ETH." },
  0x0c: { name: "V4_SWAP",                risk: "MEDIUM",  desc: "Swap through a Uniswap v4 pool." },
  0x0d: { name: "V4_POSITION_CALL",       risk: "MEDIUM",  desc: "Calls a V4 position manager." },
  0x0e: { name: "BALANCE_CHECK_ERC20",    risk: "INFO",    desc: "Asserts a minimum ERC-20 balance; reverts if not met." },
  0x0f: { name: "SEAPORT",                risk: "HIGH",    desc: "Executes an OpenSea Seaport order." },
  0x10: { name: "APPROVE_ERC20",          risk: "MEDIUM",  desc: "Sets an ERC-20 allowance." }
};

// Max depth for recursive multicall decoding (prevents runaway loops).
const MAX_DECODE_DEPTH = 4;

return { TRUSTED_DOMAINS, SEED_BLACKLIST, KNOWN_SAFE_CONTRACTS, UR_COMMANDS, MAX_DECODE_DEPTH };
})();


/* ============================================================
 * lib/decoder.js
 * ============================================================ */
const decoder_js_exports = (function() {
// lib/decoder.js - Method signature dictionary + calldata parsers.

// Known method signatures: selector -> { category, name, risk, desc }
const METHOD_DECODER = {
  // ERC-20
  "0xa9059cbb": { category: "ERC-20", name: "Token Transfer",             risk: "LOW",      desc: "Send tokens directly to another wallet." },
  "0x095ea7b3": { category: "ERC-20", name: "Token Approval (Approve)",   risk: "MEDIUM",   desc: "Allow a contract to spend your tokens. Unlimited approval lets it drain the balance later." },
  "0x23b872dd": { category: "ERC-20", name: "TransferFrom (Pull Tokens)", risk: "HIGH",     desc: "A third party pulls tokens out of your wallet. Common in marketplaces, but heavily abused by drainers." },
  "0x40c10f19": { category: "ERC-20", name: "Mint Tokens (Owner)",        risk: "INFO",     desc: "Contract mints new tokens. Only callable by authorized addresses." },
  "0x42966c68": { category: "ERC-20", name: "Burn Tokens",                risk: "LOW",      desc: "Destroy tokens from your balance." },
  "0xd0e30db0": { category: "ERC-20", name: "Deposit (Wrap ETH)",         risk: "LOW",      desc: "Wrap native ETH into WETH or deposit into a vault." },
  "0x2e1a7d4d": { category: "ERC-20", name: "Withdraw (Unwrap WETH)",     risk: "LOW",      desc: "Unwrap WETH back to native ETH." },

  // ERC-721 / ERC-1155
  "0x42842e0e": { category: "ERC-721", name: "NFT SafeTransferFrom",         risk: "HIGH",     desc: "Transfer a specific NFT out of your wallet." },
  "0xb88d4fde": { category: "ERC-721", name: "NFT SafeTransferFrom (data)",  risk: "HIGH",     desc: "Transfer a specific NFT out of your wallet with attached data." },
  "0x6352211e": { category: "ERC-721", name: "NFT Owner Of (View)",          risk: "INFO",     desc: "Read-only query - safe." },
  "0xa22cb465": { category: "ERC-721/1155", name: "Approval For All",       risk: "CRITICAL", desc: "Operator gets full control over EVERY NFT in this collection. Can withdraw all without further signatures." },
  "0xf242432a": { category: "ERC-1155", name: "ERC-1155 SafeTransferFrom",   risk: "HIGH",     desc: "Transfer an ERC-1155 token. Verify the recipient carefully." },
  "0x2eb2c2d6": { category: "ERC-1155", name: "ERC-1155 SafeBatchTransfer",  risk: "HIGH",     desc: "Batch transfer multiple ERC-1155 tokens in one call." },
  "0x6a627842": { category: "ERC-1155", name: "Mint ERC-1155 (Owner)",       risk: "INFO",     desc: "Mint new ERC-1155 tokens." },

  // DeFi / DEX
  "0x415565b0": { category: "DeFi", name: "Multi-Asset Swap",              risk: "LOW",      desc: "Swap through a DEX router." },
  "0x38ed1739": { category: "DeFi", name: "Swap Exact Tokens For Tokens",  risk: "LOW",      desc: "DEX swap: trade an exact amount of one token for another." },
  "0x8803dbee": { category: "DeFi", name: "Swap Tokens For Exact Tokens",  risk: "LOW",      desc: "DEX swap: buy an exact amount of one token by spending the other." },
  "0x7ff36ab5": { category: "DeFi", name: "Swap Exact ETH For Tokens",     risk: "LOW",      desc: "DEX swap: spend native ETH to buy tokens." },
  "0x4a25d94a": { category: "DeFi", name: "Swap Exact Tokens For ETH",     risk: "LOW",      desc: "DEX swap: sell tokens for native ETH." },
  "0xfb3bdb41": { category: "DeFi", name: "Swap ETH For Exact Tokens",     risk: "LOW",      desc: "DEX swap: spend native ETH for an exact token amount." },
  "0xe8e33700": { category: "DeFi", name: "Add Liquidity",                 risk: "LOW",      desc: "Add liquidity to a pool. You will receive LP tokens." },
  "0xbaa2abde": { category: "DeFi", name: "Remove Liquidity",              risk: "LOW",      desc: "Burn LP tokens to withdraw your share of the pool." },
  "0xa694fc3a": { category: "DeFi", name: "Stake / Deposit",               risk: "LOW",      desc: "Lock tokens inside a vault to earn yield." },
  "0x2e17de78": { category: "DeFi", name: "Unstake / Withdraw",            risk: "LOW",      desc: "Withdraw previously staked tokens." },
  "0x4e71d92d": { category: "DeFi", name: "Claim Rewards",                 risk: "LOW",      desc: "Claim accumulated staking/farming rewards." },
  "0xb6b55f25": { category: "DeFi", name: "Deposit (Vault)",               risk: "LOW",      desc: "Deposit funds into an ERC-4626 vault." },
  "0x2eee7903": { category: "DeFi", name: "Withdraw (Vault)",              risk: "LOW",      desc: "Withdraw funds from an ERC-4626 vault." },

  // NFT Marketplaces
  "0xfb0f3ee3": { category: "NFT", name: "Fulfill Order (Seaport)",         risk: "MEDIUM", desc: "Fulfill an OpenSea Seaport order. Verify the counterparty and asset being traded." },
  "0x87201b41": { category: "NFT", name: "Fulfill Advanced Order (Seaport)",risk: "MEDIUM", desc: "Fulfill a complex Seaport order with criteria-based matching." },
  "0x9a1fc3a7": { category: "NFT", name: "Cancel Order (Seaport)",          risk: "LOW",    desc: "Cancel an existing listing." },

  // Multicall
  "0xac9650d8": { category: "Multicall", name: "Multicall (bytes[])",     risk: "MEDIUM",   desc: "Bundling multiple calls into one transaction. Each subcall will be decoded." },
  "0x5ae401dc": { category: "Multicall", name: "Multicall2",               risk: "MEDIUM",   desc: "Multicall2 aggregator. Each subcall is executed in sequence." },
  "0x1745e9d0": { category: "Multicall", name: "Multicall3 aggregate3",    risk: "MEDIUM",   desc: "Multicall3 aggregator with per-call failure control. Each subcall is decoded." },
  "0xee8b7563": { category: "Multicall", name: "Multicall (uint256,bytes[])", risk: "MEDIUM", desc: "Multicall with block-number check." },

  // Uniswap Universal Router
  "0x3593564c": { category: "Universal Router", name: "Execute (commands, inputs, deadline)", risk: "HIGH", desc: "Uniswap Universal Router: a sequence of swap commands is decoded and executed in order." },
  "0x248cbc34": { category: "Universal Router", name: "Execute (commands, inputs)",            risk: "HIGH", desc: "Uniswap Universal Router: a sequence of swap commands is decoded and executed in order." },

  // Bridges
  "0x1f0464d1": { category: "Bridge", name: "Bridge Swap",                  risk: "MEDIUM",   desc: "Cross-chain bridge swap." },
  "0x8b7f1068": { category: "Bridge", name: "Across Bridge",                risk: "MEDIUM",   desc: "Across protocol bridge deposit." },
  "0x301a5c2c": { category: "Bridge", name: "Stargate Swap",                risk: "MEDIUM",   desc: "Stargate cross-chain swap." }
};

// ---------- Hex helpers ----------

function strip0x(h) { return h && h.startsWith("0x") ? h.slice(2) : h || ""; }

function sliceAddress(hex) {
  // Address is the LAST 20 bytes of a 32-byte word.
  if (!hex || hex.length < 40) return null;
  return "0x" + hex.slice(-40);
}

function sliceUint256(hex) {
  if (!hex || hex.length < 64) return "0";
  try { return BigInt("0x" + hex).toString(); } catch { return "0"; }
}

function sliceBool(hex) {
  if (!hex || hex.length < 64) return false;
  try { return BigInt("0x" + hex) !== 0n; } catch { return false; }
}

function shortAddr(a) {
  if (!a || typeof a !== "string" || a.length < 10) return a || "";
  return `${a.slice(0, 6)}...${a.slice(-4)}`;
}

function formatTokenAmount(raw, decimals = 18) {
  try {
    const big = BigInt(raw);
    const divisor = 10n ** BigInt(decimals);
    const whole = big / divisor;
    const frac = big % divisor;
    const fracStr = frac.toString().padStart(decimals, "0").slice(0, 4);
    return `${whole}.${fracStr}`.replace(/\.?0+$/, "") || "0";
  } catch { return "?"; }
}

function weiToEth(weiHex) {
  if (!weiHex) return "0";
  try {
    const big = BigInt(weiHex);
    const whole = big / 10n ** 18n;
    const frac = big % 10n ** 18n;
    const fracStr = frac.toString().padStart(18, "0").slice(0, 6);
    return `${whole}.${fracStr}`.replace(/\.?0+$/, "") || "0";
  } catch { return "?"; }
}

function getMethodId(data) {
  if (!data || data.length < 10) return null;
  return data.slice(0, 10).toLowerCase();
}

// ---------- Per-method decoders ----------

function decodeApprove(data) {
  if (data.length < 138) return null;
  const spender = sliceAddress(data.slice(34, 74));
  const amount = sliceUint256(data.slice(74, 138));
  const isUnlimited = amount === "0" || amount.length >= 60 ||
    /^f{15,}/i.test(amount);
  return { spender, amount, isUnlimited };
}

function decodeTransfer(data) {
  if (data.length < 138) return null;
  const to = sliceAddress(data.slice(34, 74));
  const amount = sliceUint256(data.slice(74, 138));
  return { recipient: to, amount };
}

function decodeTransferFrom(data) {
  if (data.length < 202) return null;
  const from = sliceAddress(data.slice(34, 74));
  const to = sliceAddress(data.slice(98, 138));
  const amount = sliceUint256(data.slice(138, 202));
  return { from, to, amount };
}

function decodeSafeTransferFrom(data) {
  if (data.length < 202) return null;
  const from = sliceAddress(data.slice(34, 74));
  const to = sliceAddress(data.slice(98, 138));
  const tokenId = sliceUint256(data.slice(138, 202));
  return { from, to, tokenId };
}

function decodeSetApprovalForAll(data) {
  if (data.length < 138) return null;
  const operator = sliceAddress(data.slice(34, 74));
  const approved = sliceBool(data.slice(74, 138));
  return { operator, approved };
}

function decodeErc1155SafeTransferFrom(data) {
  if (data.length < 266) return null;
  // (address,address,uint256,uint256,uint256,bytes)
  const from = sliceAddress(data.slice(34, 74));
  const to = sliceAddress(data.slice(98, 138));
  const id = sliceUint256(data.slice(138, 202));
  const amount = sliceUint256(data.slice(202, 266));
  return { from, to, id, amount };
}

// Main decode dispatcher. Returns null if the method is unknown.
function decodeCalldata(methodId, data) {
  if (!data || data.length < 10) return null;
  switch (methodId) {
    case "0xa9059cbb": return decodeTransfer(data);
    case "0x095ea7b3": return decodeApprove(data);
    case "0x23b872dd": return decodeTransferFrom(data);
    case "0xb88d4fde":
    case "0x42842e0e": return decodeSafeTransferFrom(data);
    case "0xa22cb465": return decodeSetApprovalForAll(data);
    case "0xf242432a": return decodeErc1155SafeTransferFrom(data);
    default: return null;
  }
}

return { strip0x, sliceAddress, sliceUint256, sliceBool, shortAddr, formatTokenAmount, weiToEth, getMethodId, decodeCalldata, METHOD_DECODER };
})();


/* ============================================================
 * lib/typosquatting.js
 * ============================================================ */
const typosquatting_js_exports = (function() {
// lib/typosquatting.js - Domain spoofing / typosquatting detection.
//
// Catches three classes of attack against WalletGuard's trusted site list:
//
//   1. Character-level typosquats
//        unisvvap.org  vs uniswap.org   (distance 2, double-tap slip)
//        uniswapp.org  vs uniswap.org   (distance 1, extra char)
//
//   2. Substring / subdomain attacks
//        uniswap.org.evil.com   (contains "uniswap.org" but is not it)
//
//   3. IDN / homoglyph attacks
//        unicwap.org with Cyrillic 'а' (visually identical to Latin 'a')
//
// Design notes:
//   - We compare eTLD+1 (last 2 labels) so that "app.uniswap.org" and
//     "blog.uniswap.org" are recognized as the same registrable domain
//     as "uniswap.org". This is a deliberately simple heuristic — all
//     domains in TRUSTED_DOMAINS are 2-label.
//   - Levenshtein threshold scales with length: ≤2 for short names,
//     ≤3 for longer ones (≤3 catches "unisvvap.org" without flooding
//     the user with false positives on random short sites).
//   - Pure module: no DOM, no globals. Safe to import from anywhere.

// ---------- Pure helpers ----------

/**
 * Iterative Levenshtein distance with O(min(a,b)) memory.
 * Returns the minimum number of single-character edits (insertions,
 * deletions, substitutions) required to transform `a` into `b`.
 */
function levenshtein(a, b) {
  if (a === b) return 0;
  const al = a.length;
  const bl = b.length;
  if (al === 0) return bl;
  if (bl === 0) return al;

  // Iterate over the shorter string in the inner loop.
  let s, t;
  if (al <= bl) { s = a; t = b; }
  else          { s = b; t = a; }

  const sl = s.length;
  const tl = t.length;
  const prev = new Array(sl + 1);
  const curr = new Array(sl + 1);

  for (let i = 0; i <= sl; i++) prev[i] = i;

  for (let j = 1; j <= tl; j++) {
    curr[0] = j;
    const tc = t.charCodeAt(j - 1);
    for (let i = 1; i <= sl; i++) {
      const cost = s.charCodeAt(i - 1) === tc ? 0 : 1;
      curr[i] = Math.min(
        prev[i] + 1,        // deletion from t
        curr[i - 1] + 1,    // insertion into t
        prev[i - 1] + cost  // substitution
      );
    }
    for (let i = 0; i <= sl; i++) prev[i] = curr[i];
  }

  return prev[sl];
}

/**
 * Extract the registrable domain (eTLD+1) by taking the last two labels.
 * Good enough for the .com/.org/.io/.fi/.xyz universe covered by
 * TRUSTED_DOMAINS. Multi-segment public suffixes (.co.uk, .com.au)
 * are out of scope for this MVP.
 */
function getRegistrableDomain(hostname) {
  if (!hostname) return "";
  const parts = hostname.toLowerCase().split(".").filter(Boolean);
  if (parts.length <= 2) return parts.join(".");
  return parts.slice(-2).join(".");
}

/**
 * Strip leading "www." (case-insensitive). Common convention for
 * canonical form: "www.uniswap.org" and "uniswap.org" are the same site.
 */
function stripWww(host) {
  return host.replace(/^www\./, "");
}

/**
 * Distance threshold for a given trusted domain. Short names are
 * prone to false positives at distance 3 (e.g. "curve.fi" vs many
 * random .fi sites), so we tighten the threshold below 10 chars.
 */
function thresholdFor(len) {
  return len <= 10 ? 2 : 3;
}

// ---------- Public API ----------

/**
 * Inspect a hostname for typosquatting / impersonation attempts.
 *
 * @param {string} hostname - window.location.hostname or equivalent.
 * @returns {null | {
 *   type: "trusted" | "typosquat" | "subdomain-attack" | "homoglyph",
 *   match: string,        // which trusted domain triggered the verdict
 *   distance?: number,    // only set for type === "typosquat"
 *   hostname: string      // normalized input
 * }}
 *
 * Resolution order:
 *   1. Exact match against any TRUSTED_DOMAINS entry, or against the
 *      registrable form of the hostname → trusted.
 *   2. Hostname contains a trusted domain as a non-registrable substring
 *      (e.g. "uniswap.org.evil.com") → subdomain-attack.
 *   3. Non-ASCII characters in hostname → homoglyph (IDN attack).
 *   4. Levenshtein distance from registrable to any trusted domain is
 *      within threshold → typosquat.
 *   5. Otherwise null.
 */
function findTyposquatting(hostname) {
  if (!hostname || typeof hostname !== "string") return null;

  const host = stripWww(hostname.toLowerCase().trim());
  if (!host) return null;

  const registrable = getRegistrableDomain(host);

  // 1. Trusted (exact match against either full host or eTLD+1).
  for (const trusted of TRUSTED_DOMAINS) {
    if (trusted === host || trusted === registrable) {
      return { type: "trusted", match: trusted, hostname: host };
    }
  }

  // 2. Substring / subdomain impersonation.
  //    "uniswap.org.evil.com" contains "uniswap.org" but its eTLD+1
  //    is "evil.com". A naive Levenshtein won't catch this because
  //    the strings are very different lengths.
  for (const trusted of TRUSTED_DOMAINS) {
    if (host.includes(trusted)) {
      return { type: "subdomain-attack", match: trusted, hostname: host };
    }
  }

  // 3. IDN / homoglyph. Any non-ASCII character in a domain that
  //    *looks* ASCII is a classic phishing trick (Cyrillic 'а' vs
  //    Latin 'a'). Modern browsers render these in Punycode (xn--),
  //    so we check the raw hostname first and the Punycode form
  //    second.
  if (/[^\x00-\x7F]/.test(host)) {
    for (const trusted of TRUSTED_DOMAINS) {
      if (host.includes(trusted.split(".")[0])) {
        return { type: "homoglyph", match: trusted, hostname: host };
      }
    }
    // Non-ASCII but no obvious trusted substring: still suspicious.
    return { type: "homoglyph", match: null, hostname: host };
  }

  // 4. Levenshtein typosquat.
  let best = null;
  for (const trusted of TRUSTED_DOMAINS) {
    const dist = levenshtein(registrable, trusted);
    if (dist === 0) continue; // already handled by step 1
    const t = thresholdFor(trusted.length);
    if (dist > t) continue;
    if (!best || dist < best.distance) {
      best = { type: "typosquat", match: trusted, distance: dist, hostname: host };
    }
  }

  return best;
}

return { levenshtein, getRegistrableDomain, findTyposquatting };
})();


/* ============================================================
 * lib/multicall-decoder.js
 * ============================================================ */
const multicall_decoder_js_exports = (function() {
// lib/multicall-decoder.js - Recursive decoder for Multicall variants.
//
// Supported method signatures:
//   0xac9650d8 - multicall(bytes[] calldatas)                       - Multicall (V1)
//   0xee8b7563 - multicall(uint256 blockNumber, bytes[] calldatas)  - Multicall2
//   0x1745e9d0 - aggregate3((address,bool,bytes)[])                 - Multicall3
//   0x4b1f6190 - aggregate((address,bytes)[])                       - Multicall3
//   0x399960fc - tryAggregate(bool,(address,bytes)[])                - Multicall3
//   0xd1150700 - tryBlockAndAggregate(bool,uint256,(address,bytes)[])
//   0x3975e40a - aggregate3Value((address,bool,uint256,bytes)[])    - Multicall3

const MULTICALL_METHODS = new Set([
  "0xac9650d8", "0xee8b7563", "0x1745e9d0",
  "0x4b1f6190", "0x399960fc", "0xd1150700", "0x3975e40a"
]);

function isMulticall(methodId) {
  return MULTICALL_METHODS.has(methodId);
}

// ---------- Helpers ----------

function readWord(hex, pos) {
  if (pos + 64 > hex.length) return { value: null, next: pos };
  return { value: hex.slice(pos, pos + 64), next: pos + 64 };
}

// ---------- Decoders ----------

// Decode multicall(bytes[]) - 0xac9650d8
// Layout: [selector][offset=0x20][length][for each: offset, length, data]
function decodeMulticallV1(hex) {
  const lengthWord = hex.slice(64, 128);
  let length;
  try { length = Number(BigInt("0x" + lengthWord)); } catch { return []; }

  const calls = [];
  let cursor = 128;
  for (let i = 0; i < length; i++) {
    if (cursor + 64 > hex.length) break;
    const offsetWord = hex.slice(cursor, cursor + 64);
    let offsetBytes;
    try { offsetBytes = Number(BigInt("0x" + offsetWord)) * 2; } catch { break; }
    // Offsets inside a bytes[] point from the start of the array argument
    // (which is at hex position 64 in this calldata layout).
    const dataStart = 64 + offsetBytes;
    if (dataStart + 64 > hex.length) break;

    const lenWord = hex.slice(dataStart, dataStart + 64);
    let callLen;
    try { callLen = Number(BigInt("0x" + lenWord)); } catch { break; }
    const callHex = hex.slice(dataStart + 64, dataStart + 64 + callLen * 2);
    if (callHex.length >= 8) calls.push("0x" + callHex);

    const padded = Math.ceil(callLen / 32) * 32;
    cursor = Math.max(cursor + 64, dataStart + 64 + padded * 2);
  }
  return calls;
}

// Decode multicall(uint256 blockNumber, bytes[] calldatas) - 0xee8b7563
// The uint256 sits at the start, then bytes[] follows.
function decodeMulticallWithBlock(hex) {
  // bytes[] starts at position 64 (after the uint256).
  // Inside the bytes[], the first word is the offset (always 0x20 = 64 bytes = 128 hex chars).
  const offsetWord = hex.slice(64, 128);
  let arrOffset;
  try { arrOffset = Number(BigInt("0x" + offsetWord)) * 2; } catch { return []; }
  // arrOffset is from start of the bytes[] argument (position 64 in the original calldata).
  const lengthStart = 64 + arrOffset;
  if (lengthStart + 64 > hex.length) return [];
  const lengthWord = hex.slice(lengthStart, lengthStart + 64);
  let length;
  try { length = Number(BigInt("0x" + lengthWord)); } catch { return []; }

  const calls = [];
  let cursor = lengthStart + 64;
  for (let i = 0; i < length; i++) {
    if (cursor + 64 > hex.length) break;
    const offW = hex.slice(cursor, cursor + 64);
    let offsetBytes;
    try { offsetBytes = Number(BigInt("0x" + offW)) * 2; } catch { break; }
    const dataStart = lengthStart + offsetBytes;
    if (dataStart + 64 > hex.length) break;
    const lenWord = hex.slice(dataStart, dataStart + 64);
    let callLen;
    try { callLen = Number(BigInt("0x" + lenWord)); } catch { break; }
    const callHex = hex.slice(dataStart + 64, dataStart + 64 + callLen * 2);
    if (callHex.length >= 8) calls.push("0x" + callHex);
    const padded = Math.ceil(callLen / 32) * 32;
    cursor = Math.max(cursor + 64, dataStart + 64 + padded * 2);
  }
  return calls;
}

// Decode aggregate3((address,bool,bytes)[]) - 0x1745e9d0
// Also handles aggregate (0x4b1f6190), tryAggregate (0x399960fc),
// tryBlockAndAggregate (0xd1150700), aggregate3Value (0x3975e40a).
function decodeAggregate3(hex) {
  const lengthWord = hex.slice(64, 128);
  let length;
  try { length = Number(BigInt("0x" + lengthWord)); } catch { return []; }

  const headsStart = 136; // in hex chars (selector=8 + offset=64 + length=64)
  const heads = [];
  for (let i = 0; i < length; i++) {
    // Each head is 96 bytes = 192 hex chars.
    const headPos = headsStart + i * 192;
    if (headPos + 192 > hex.length) break;
    // Address occupies the last 20 bytes (40 hex chars) of the first 32-byte word.
    const address = "0x" + hex.slice(headPos + 24, headPos + 64);
    // Bool is the second 32-byte word.
    const successWord = hex.slice(headPos + 64, headPos + 128);
    // Offset is the third 32-byte word (in bytes from head start).
    const offsetWord = hex.slice(headPos + 128, headPos + 192);
    let bytesOffsetBytes;
    try { bytesOffsetBytes = Number(BigInt("0x" + offsetWord)); } catch { continue; }
    const bytesOffset = bytesOffsetBytes * 2; // convert bytes to hex chars
    heads.push({ headPos, address, successWord, bytesOffset });
  }

  const calls = [];
  for (const h of heads) {
    const tailStart = h.headPos + h.bytesOffset;
    if (tailStart + 64 > hex.length) continue;
    const lenWord = hex.slice(tailStart, tailStart + 64);
    let callLen;
    try { callLen = Number(BigInt("0x" + lenWord)); } catch { continue; }
    const callHex = hex.slice(tailStart + 64, tailStart + 64 + callLen * 2);
    if (callHex.length >= 8) {
      calls.push({
        target: h.address,
        data: "0x" + callHex
      });
    }
  }
  return calls;
}

// ---------- Top-level entry ----------

// Returns an array of { target, data } objects for inner calls in a multicall.
// `target` may be null for V1 multicall where per-call addresses aren't encoded.
// Empty array if the method is not recognized or decoding fails.
function extractInnerCalls(methodId, fullData) {
  const hex = strip0x(fullData);
  if (hex.length < 8) return [];

  try {
    if (methodId === "0xac9650d8") return decodeMulticallV1(hex).map((c) => ({ target: null, data: c }));
    if (methodId === "0xee8b7563") return decodeMulticallWithBlock(hex).map((c) => ({ target: null, data: c }));
    if (MULTICALL_METHODS.has(methodId)) return decodeAggregate3(hex);
  } catch (e) {
    console.warn("WalletGuard: multicall decode failed:", e);
  }
  return [];
}

return { isMulticall, extractInnerCalls };
})();


/* ============================================================
 * lib/universal-router.js
 * ============================================================ */
const universal_router_js_exports = (function() {
// lib/universal-router.js - Uniswap Universal Router command parser.
//
// Supported signatures:
//   0x3593564c - execute(bytes commands, bytes[] inputs, uint256 deadline)
//   0x248cbc34 - execute(bytes commands, bytes[] inputs)
//
// Reference: https://docs.uniswap.org/contracts/universal-router/technical-reference


const UR_METHODS = new Set(["0x3593564c", "0x248cbc34"]);

function isUniversalRouter(methodId) {
  return UR_METHODS.has(methodId);
}

// Decode a single command byte -> { name, risk, desc } from UR_COMMANDS.
function describeCommand(byte) {
  return UR_COMMANDS[byte] || {
    name: `UNKNOWN(0x${byte.toString(16).padStart(2, "0")})`,
    risk: "MEDIUM",
    desc: "Unknown Universal Router command. Verify the dApp before proceeding."
  };
}

// Try to extract a human-readable hint from the input bytes of a command.
// Inputs are router-specific (mostly encoded swap routes); we surface the
// first 20 bytes worth of hex so users can at least see what each command touches.
function inputPreview(inputHex) {
  if (!inputHex || inputHex.length < 4) return "";
  // Take first 10 hex chars (5 bytes) as a hint — enough to spot addresses.
  return inputHex.slice(0, 20);
}

// Decode Universal Router execute(...).
// Returns { commands: [{ byte, name, risk, desc, inputPreview }], deadline }
function decodeUniversalRouter(fullData) {
  const hex = strip0x(fullData);
  if (hex.length < 8) return null;

  // Determine deadline position based on which execute variant we have.
  // For 0x3593564c: args = (offset_cmd, offset_inputs, deadline)
  //   cmd offset at byte 4, inputs offset at byte 36, deadline at byte 68.
  // For 0x248cbc34: args = (offset_cmd, offset_inputs)
  //   cmd offset at byte 4, inputs offset at byte 36, no deadline.
  const cmdOffsetWord = hex.slice(8, 72);
  const inputsOffsetWord = hex.slice(72, 136);
  let cmdOffsetBytes, inputsOffsetBytes;
  try {
    cmdOffsetBytes = Number(BigInt("0x" + cmdOffsetWord)) * 2;
    inputsOffsetBytes = Number(BigInt("0x" + inputsOffsetWord)) * 2;
  } catch {
    return null;
  }

  // Bytes start at byte 4 (after selector). Offsets are relative to that point.
  const cmdStart = 8 + cmdOffsetBytes;
  const inputsStart = 8 + inputsOffsetBytes;

  // Read commands bytes
  if (cmdStart + 64 > hex.length) return null;
  const cmdLenWord = hex.slice(cmdStart, cmdStart + 64);
  let cmdLen;
  try { cmdLen = Number(BigInt("0x" + cmdLenWord)); } catch { return null; }
  const cmdBytesHex = hex.slice(cmdStart + 64, cmdStart + 64 + cmdLen * 2);

  // Read inputs[]
  if (inputsStart + 64 > hex.length) return null;
  const inputsLenWord = hex.slice(inputsStart, inputsStart + 64);
  let inputsLen;
  try { inputsLen = Number(BigInt("0x" + inputsLenWord)); } catch { return null; }

  // Each input is a dynamic bytes: (offset, length, data)
  const inputs = [];
  let cursor = inputsStart + 64;
  for (let i = 0; i < inputsLen; i++) {
    if (cursor + 64 > hex.length) break;
    const offW = hex.slice(cursor, cursor + 64);
    let offsetBytes;
    try { offsetBytes = Number(BigInt("0x" + offW)) * 2; } catch { break; }
    const dataStart = inputsStart + offsetBytes;
    if (dataStart + 64 > hex.length) break;
    const lenW = hex.slice(dataStart, dataStart + 64);
    let len;
    try { len = Number(BigInt("0x" + lenW)); } catch { break; }
    const inputHex = hex.slice(dataStart + 64, dataStart + 64 + len * 2);
    inputs.push(inputHex);
    const padded = Math.ceil(len / 32) * 32;
    cursor = Math.max(cursor + 64, dataStart + 64 + padded * 2);
  }

  // Parse command bytes (1 byte each)
  const commands = [];
  for (let i = 0; i < cmdLen; i++) {
    const byteHex = cmdBytesHex.slice(i * 2, i * 2 + 2);
    if (byteHex.length < 2) break;
    const byte = parseInt(byteHex, 16);
    const meta = describeCommand(byte);
    commands.push({
      byte,
      index: i,
      name: meta.name,
      risk: meta.risk,
      desc: meta.desc,
      inputPreview: inputPreview(inputs[i] || "")
    });
  }

  return { commands, inputs };
}

return { isUniversalRouter, decodeUniversalRouter };
})();


/* ============================================================
 * lib/risk-engine.js
 * ============================================================ */
const risk_engine_js_exports = (function() {
// lib/risk-engine.js - Weighted risk scoring with factor explanations.
//
// The engine is data-driven: each rule adds a "factor" with a weight.
// The final trust score is 100 - sum(weights), clamped to [0, 100].
// The UI shows the user WHY the score is what it is.



// ---------- Factor helpers ----------

const factor = (name, weight, severity, description) => ({
  name, weight, severity, description
});

// ---------- Rule: target & value ----------

function evaluateTarget(ctx) {
  const factors = [];
  const target = (ctx.target || "").toLowerCase();

  if (target && KNOWN_SAFE_CONTRACTS.has(target)) {
    factors.push(factor(
      "Verified Protocol Contract",
      -20, "positive",
      `${shortAddr(ctx.target)} is in the WalletGuard trust database.`
    ));
  } else if (target && ctx.data && ctx.data !== "0x") {
    factors.push(factor(
      "Unknown Contract",
      +10, "medium",
      `${shortAddr(ctx.target)} is not in the local verified contract registry.`
    ));
  } else if (target && (!ctx.data || ctx.data === "0x")) {
    // Plain ETH transfer - target is the recipient address.
    factors.push(factor(
      "Unknown Recipient",
      +10, "medium",
      `${shortAddr(ctx.target)} is not in the verified recipient list.`
    ));
  }

  if (ctx.from && target && ctx.from.toLowerCase() === target) {
    factors.push(factor(
      "Self-Send",
      +10, "medium",
      "Sender and recipient are the same address. Unusual, may indicate a setup call."
    ));
  }

  if (ctx.ethFloat >= 5) {
    factors.push(factor(
      `Large ETH Transfer (${ctx.ethValue} ETH)`,
      +30, "high",
      "Outflows of 5+ ETH are commonly targeted by drainers."
    ));
  } else if (ctx.ethFloat >= 1) {
    factors.push(factor(
      `Medium ETH Transfer (${ctx.ethValue} ETH)`,
      +15, "medium",
      "Outflows of 1+ ETH warrant attention."
    ));
  } else if (ctx.ethFloat > 0) {
    factors.push(factor(
      `Outbound ETH (${ctx.ethValue} ETH)`,
      +5, "low",
      "Small native ETH outflow."
    ));
  }

  return factors;
}

// ---------- Rule: methods & decoded args ----------

function evaluateMethods(ctx) {
  const factors = [];
  const methodId = getMethodId(ctx.data || "");

  if (!methodId) return factors;

  switch (methodId) {
    case "0x095ea7b3": { // approve
      if (ctx.decoded && ctx.decoded.isUnlimited) {
        factors.push(factor(
          "Unlimited Token Approval",
          +30, "high",
          `${shortAddr(ctx.decoded.spender)} can withdraw ALL of this token from your wallet at any time.`
        ));
      } else if (ctx.decoded) {
        factors.push(factor(
          "Limited Token Approval",
          +8, "low",
          `Approval is capped to a specific amount; still exposes funds if the spender is malicious.`
        ));
      }
      break;
    }
    case "0xa22cb465": { // setApprovalForAll
      factors.push(factor(
        "NFT Approval For All",
        +40, "critical",
        `${shortAddr(ctx.decoded?.operator)} gains root access to EVERY NFT in this collection.`
      ));
      break;
    }
    case "0x23b872dd": { // transferFrom
      factors.push(factor(
        "TransferFrom (Pull Tokens)",
        +20, "high",
        "A third party is pulling tokens out of your wallet. Top method used by drainers."
      ));
      break;
    }
    case "0x42842e0e":
    case "0xb88d4fde": { // NFT safeTransferFrom
      factors.push(factor(
        "NFT Outflow",
        +15, "medium",
        `NFT #${ctx.decoded?.tokenId || "?"} will leave your wallet.`
      ));
      break;
    }
    case "0xac9650d8":
    case "0x5ae401dc":
    case "0x1745e9d0":
    case "0xee8b7563": { // multicall
      factors.push(factor(
        "Multicall Wrapper",
        +5, "low",
        `Bundles ${ctx.innerCalls?.length || "?"} subcall(s). Each is decoded below.`
      ));
      break;
    }
    case "0x3593564c":
    case "0x248cbc34": { // Universal Router execute
      factors.push(factor(
        "Universal Router (Uniswap)",
        0, "info",
        `Executes ${ctx.urCommands?.length || "?"} router command(s) in sequence.`
      ));
      break;
    }
    case "0x1f0464d1":
    case "0x8b7f1068":
    case "0x301a5c2c": { // Bridges
      factors.push(factor(
        "Bridge Transaction",
        +5, "low",
        "Cross-chain bridge. Verify the destination chain and asset carefully."
      ));
      break;
    }
  }

  if (ctx.unknownMethod) {
    factors.push(factor(
      "Unknown Method",
      +8, "low",
      `Method ${methodId} is not in the local signature library.`
    ));
  }

  // Recursive: each inner call contributes its own factors.
  if (ctx.innerFactors && ctx.innerFactors.length) {
    for (const inner of ctx.innerFactors) {
      factors.push(...inner.factors);
    }
  }

  return factors;
}

// ---------- Rule: signatures ----------

function evaluateSignature(ctx) {
  const factors = [];
  if (ctx.isEIP712 && ctx.permitDetails) {
    const unlimited = ctx.permitDetails.value === "Unlimited" ||
      /^f{15,}/i.test(ctx.permitDetails.value);
    factors.push(factor(
      unlimited ? "Unlimited Permit (off-chain)" : "Limited Permit (off-chain)",
      unlimited ? +40 : +20,
      unlimited ? "critical" : "high",
      unlimited
        ? `Off-chain signature granting UNLIMITED spending to ${ctx.permitDetails.spender}.`
        : `Off-chain signature allowing ${ctx.permitDetails.value} spend via ${ctx.permitDetails.spender}.`
    ));
  }
  if (ctx.isPersonalSign || ctx.isLegacySign) {
    factors.push(factor(
      "Blind Signature",
      +15, "medium",
      "Signing arbitrary data off-chain. Phishers encode Permit/Order payloads here."
    ));
  }
  return factors;
}

// ---------- Rule: whitelist bonus ----------

function evaluateWhitelist(ctx) {
  const factors = [];
  const target = (ctx.target || "").toLowerCase();
  if (target && ctx.trustedAddresses && ctx.trustedAddresses.has(target)) {
    factors.push(factor(
      "Whitelisted Address",
      -15, "positive",
      `${shortAddr(ctx.target)} is in your personal whitelist.`
    ));
  }
  return factors;
}

// ---------- Rule: domain impersonation (typosquatting) ----------

function evaluateDomain(ctx) {
  if (!ctx.hostname) return [];
  const verdict = findTyposquatting(ctx.hostname);
  if (!verdict) return [];

  if (verdict.type === "trusted") {
    return [factor(
      "Trusted Site",
      -15, "positive",
      `${ctx.hostname} matches a known-good protocol (${verdict.match}).`
    )];
  }

  if (verdict.type === "typosquat") {
    return [factor(
      "Possible Typosquatting",
      +40, "critical",
      `${ctx.hostname} is ${verdict.distance} character(s) away from ${verdict.match}. ` +
      `This is a common phishing tactic — verify the URL before approving.`
    )];
  }

  if (verdict.type === "subdomain-attack") {
    return [factor(
      "Subdomain Impersonation",
      +45, "critical",
      `${ctx.hostname} contains "${verdict.match}" but its real domain is different. ` +
      `Classic phishing pattern — the trusted name is a subdomain, not the real site.`
    )];
  }

  if (verdict.type === "homoglyph") {
    const target = verdict.match
      ? `looks identical to ${verdict.match}`
      : "uses non-ASCII characters that may mimic a trusted site";
    return [factor(
      "IDN / Homoglyph Attack",
      +45, "critical",
      `${ctx.hostname} ${target}. Internationalized domain names are a known phishing vector.`
    )];
  }

  return [];
}

// ---------- Score derivation ----------

function levelFromScore(score) {
  if (score < 30) return { level: "CRITICAL RISK", color: "#ff3333" };
  if (score < 55) return { level: "HIGH RISK",    color: "#ff4d4d" };
  if (score < 75) return { level: "WARNING",      color: "#ffb700" };
  if (score < 90) return { level: "LOW RISK",     color: "#00ff66" };
  return           { level: "SAFE",          color: "#00ffcc" };
}

// ---------- Public API ----------

// ctx = {
//   target, from, value, data, ethValue, ethFloat,
//   decoded, unknownMethod,
//   innerCalls, innerFactors,
//   urCommands,
//   isEIP712, isPersonalSign, isLegacySign, permitDetails,
//   trustedAddresses,
//   hostname             // window.location.hostname (without leading www.)
// }
//
// Returns { trustScore, riskLevel, accentColor, factors, domainVerdict }
function computeRisk(ctx) {
  const domainVerdict = ctx.hostname ? findTyposquatting(ctx.hostname) : null;

  const factors = [
    ...evaluateTarget(ctx),
    ...evaluateMethods(ctx),
    ...evaluateSignature(ctx),
    ...evaluateWhitelist(ctx),
    ...evaluateDomain(ctx)
  ];

  // Compound rules — combinations of factors that amplify risk.
  const has = (name) => factors.some((f) => f.name === name);
  const target = (ctx.target || "").toLowerCase();
  const isVerified = KNOWN_SAFE_CONTRACTS.has(target);
  const isWhitelisted = ctx.trustedAddresses && ctx.trustedAddresses.has(target);

  if (has("Unlimited Token Approval") && !isVerified && !isWhitelisted) {
    factors.push(factor(
      "Compound: Unlimited Approval to Unverified Contract",
      +25, "critical",
      "This is the exact pattern used by drainer sites."
    ));
  }

  if (has("NFT Approval For All") && !isVerified && !isWhitelisted) {
    factors.push(factor(
      "Compound: NFT Root Access to Unverified Contract",
      +20, "critical",
      "Full NFT custody to an unverified operator is a top drainer tactic."
    ));
  }

  if (has("TransferFrom (Pull Tokens)") && has("Unknown Contract")) {
    factors.push(factor(
      "Compound: Pull Tokens from Unverified Source",
      +15, "high",
      "Pulling tokens from an unverified contract — common drainer pattern."
    ));
  }

  if (has("Unknown Recipient") && ctx.ethFloat >= 1) {
    factors.push(factor(
      "Compound: Native ETH to Unverified Address",
      +20, "high",
      "Sending native ETH to an unverified recipient. Double-check the address."
    ));
  }

  const totalWeight = factors.reduce((sum, f) => sum + f.weight, 0);
  const rawScore = 100 - totalWeight;
  const trustScore = Math.max(0, Math.min(100, Math.round(rawScore)));

  const { level, color } = levelFromScore(trustScore);

  return {
    trustScore,
    riskLevel: level,
    accentColor: color,
    factors,
    domainVerdict
  };
}

return { computeRisk };
})();


/* ============================================================
 * lib/capabilities.js
 * ============================================================ */
const capabilities_js_exports = (function() {
// lib/capabilities.js - Rich explanations of what a transaction/signature enables.
//
// Each capability is a short sentence that the UI shows under
// "What this lets the contract do" so the user understands the long-term
// consequences, not just the immediate action.

// ---------- Per-method capabilities ----------

function approveCapabilities(decoded) {
  if (!decoded) return [];
  if (decoded.isUnlimited) {
    return [
      `${shortAddr(decoded.spender)} can transfer UNLIMITED of this token from your wallet at any time.`,
      `You can revoke the approval later via revoke.cash or directly through the contract.`,
      `If ${shortAddr(decoded.spender)} is hacked or malicious, ALL of this token can be drained.`
    ];
  }
  return [
    `${shortAddr(decoded.spender)} can transfer up to ${formatTokenAmount(decoded.amount)} tokens from your wallet.`,
    `The allowance expires only when you spend it or revoke it.`
  ];
}

function setApprovalForAllCapabilities(decoded) {
  if (!decoded) return [];
  return [
    `${shortAddr(decoded.operator)} can transfer EVERY NFT in this collection from your wallet without further signatures.`,
    `Includes NFTs you may receive later in the same collection.`,
    `Revoke via setApprovalForAll(operator, false) or revoke.cash.`
  ];
}

function transferFromCapabilities(decoded) {
  if (!decoded) return [];
  return [
    `A contract is pulling ${formatTokenAmount(decoded.amount)} tokens from your wallet on your behalf.`,
    `Requires prior approval or allowance to the caller.`
  ];
}

function safeTransferFromCapabilities(decoded) {
  if (!decoded) return [];
  return [
    `NFT #${decoded.tokenId || "?"} will be transferred to ${shortAddr(decoded.to)}.`,
    `This is irreversible once confirmed.`
  ];
}

function swapCapabilities(decoded, ethValue) {
  const lines = [
    `Exchanges one token for another through a DEX pool.`,
    `Slippage settings, MEV bots, and pool depth all affect the final amount.`
  ];
  if (ethValue && parseFloat(ethValue) > 0) {
    lines.push(`${ethValue} ETH will be spent from your balance.`);
  }
  return lines;
}

function multicallCapabilities(innerCount) {
  return [
    `Bundles ${innerCount} subcall(s) into one transaction.`,
    `If allowFailure=false on any subcall and that subcall fails, the whole transaction reverts.`,
    `Subcall breakdown is shown below.`
  ];
}

function universalRouterCapabilities(cmdCount) {
  return [
    `Uniswap Universal Router will execute ${cmdCount} command(s) in sequence.`,
    `Each command can transfer, swap, or grant allowances.`,
    `Commands are decoded below.`
  ];
}

function permitCapabilities(pd) {
  const unlimited = pd.value === "Unlimited" || /^f{15,}/i.test(pd.value);
  const lines = [
    `Off-chain signature - no gas is paid and no transaction appears on-chain.`,
    `${shortAddr(pd.spenderFull || pd.spender)} can call transferFrom on your ${pd.tokenName} until revoked or expired.`
  ];
  if (unlimited) {
    lines.push(`UNLIMITED allowance granted - the spender can drain ALL of this token.`);
  } else {
    lines.push(`Allowance: ${pd.value} tokens.`);
  }
  if (pd.deadline) {
    lines.push(`Valid until: ${pd.deadline}.`);
  }
  return lines;
}

function bridgeCapabilities() {
  return [
    `Tokens will be bridged to another chain.`,
    `Bridging is irreversible - wrong chain means lost funds.`,
    `Verify the destination chain in the dApp UI.`
  ];
}

function personalSignCapabilities() {
  return [
    `Signs an arbitrary off-chain message.`,
    `Legitimate dApps use this for logins, but phishers may encode Permit/Order payloads.`,
    `Never sign a hex blob you cannot decode.`
  ];
}

// ---------- Top-level entry ----------

// Returns an array of capability strings to display in the UI.
function describeCapabilities(ctx) {
  const methodId = getMethodId(ctx.data || "");
  const caps = [];

  if (ctx.isEIP712 && ctx.permitDetails) {
    caps.push(...permitCapabilities(ctx.permitDetails));
    return caps;
  }
  if (ctx.isPersonalSign) {
    caps.push(...personalSignCapabilities());
    return caps;
  }
  if (ctx.isLegacySign) {
    caps.push(
      `Legacy eth_sign - signs an arbitrary hash with no readable payload.`,
      `Consider this dangerous unless you trust the dApp fully.`
    );
    return caps;
  }

  switch (methodId) {
    case "0x095ea7b3": caps.push(...approveCapabilities(ctx.decoded)); break;
    case "0xa22cb465": caps.push(...setApprovalForAllCapabilities(ctx.decoded)); break;
    case "0x23b872dd": caps.push(...transferFromCapabilities(ctx.decoded)); break;
    case "0x42842e0e":
    case "0xb88d4fde": caps.push(...safeTransferFromCapabilities(ctx.decoded)); break;
    case "0x38ed1739":
    case "0x8803dbee":
    case "0x7ff36ab5":
    case "0x4a25d94a":
    case "0xfb3bdb41":
    case "0x415565b0": caps.push(...swapCapabilities(ctx.decoded, ctx.ethValue)); break;
    case "0xac9650d8":
    case "0x5ae401dc":
    case "0x1745e9d0":
    case "0xee8b7563": caps.push(...multicallCapabilities(ctx.innerCalls?.length || 0)); break;
    case "0x3593564c":
    case "0x248cbc34": caps.push(...universalRouterCapabilities(ctx.urCommands?.length || 0)); break;
    case "0x1f0464d1":
    case "0x8b7f1068":
    case "0x301a5c2c": caps.push(...bridgeCapabilities()); break;
  }

  if (caps.length === 0) {
    caps.push(
      "No specific capabilities flagged for this call.",
      "Always verify the dApp URL and the recipient contract before confirming."
    );
  }

  return caps;
}

return { describeCapabilities };
})();


/* ============================================================
 * lib/simulator.js
 * ============================================================ */
const simulator_js_exports = (function() {
// lib/simulator.js - Asset Diff Engine.
//
// Produces a list of asset changes ("OUT: 0.5 ETH", "IN: 100 USDC") for display.
// Without an RPC connection we can only produce best-effort estimates from the
// decoded calldata; we surface that uncertainty to the user instead of guessing.

const ETH = "ETH";
const UNKNOWN_TOKEN = "TOKEN";

// Internal representation of an asset change.
function diff(symbol, sent, received, note) {
  return { symbol, sent, received, note };
}

function empty() {
  return { lines: [], summary: "No balance changes detected.", totalOutEth: 0, totalInEth: 0 };
}

// ---------- Per-method diff ----------

function diffApprove(decoded) {
  if (!decoded) return empty();
  if (decoded.isUnlimited) {
    return {
      lines: [diff(UNKNOWN_TOKEN, "UNLIMITED", "0",
        `Full allowance to ${shortAddr(decoded.spender)}. Future calls can drain ALL.` )],
      summary: "No immediate balance change. Unlimited allowance granted.",
      totalOutEth: 0, totalInEth: 0,
      risk: "unlimited-allowance"
    };
  }
  return {
    lines: [diff(UNKNOWN_TOKEN, formatTokenAmount(decoded.amount), "0",
      `Capped allowance to ${shortAddr(decoded.spender)}.` )],
    summary: `No immediate balance change. ${formatTokenAmount(decoded.amount)} tokens approved.`,
    totalOutEth: 0, totalInEth: 0
  };
}

function diffSetApprovalForAll(decoded) {
  if (!decoded) return empty();
  return {
    lines: [diff("NFTs", "ALL", "0",
      `Full operator rights to ${shortAddr(decoded.operator)}.` )],
    summary: "No immediate balance change. Every NFT in this collection is exposed.",
    totalOutEth: 0, totalInEth: 0,
    risk: "unlimited-allowance"
  };
}

function diffTransfer(decoded, ethValue) {
  if (!decoded) return empty();
  const lines = [];
  const outEth = parseFloat(ethValue) || 0;
  if (outEth > 0) lines.push(diff(ETH, ethValue, "0", "Direct native transfer"));
  lines.push(diff(UNKNOWN_TOKEN, formatTokenAmount(decoded.amount), "0",
    `Sent to ${shortAddr(decoded.recipient)}.` ));
  return {
    lines,
    summary: outEth > 0
      ? `OUT ${ethValue} ETH + ${formatTokenAmount(decoded.amount)} tokens`
      : `OUT ${formatTokenAmount(decoded.amount)} tokens`,
    totalOutEth: outEth, totalInEth: 0
  };
}

function diffTransferFrom(decoded) {
  if (!decoded) return empty();
  return {
    lines: [diff(UNKNOWN_TOKEN, formatTokenAmount(decoded.amount), "0",
      `Pulled from your wallet to ${shortAddr(decoded.to)}.` )],
    summary: `OUT ${formatTokenAmount(decoded.amount)} tokens`,
    totalOutEth: 0, totalInEth: 0
  };
}

function diffSafeTransferFrom(decoded) {
  if (!decoded) return empty();
  return {
    lines: [diff("NFT", `#${decoded.tokenId || "?"}`, "0",
      `Sent to ${shortAddr(decoded.to)}.` )],
    summary: `OUT NFT #${decoded.tokenId || "?"}`,
    totalOutEth: 0, totalInEth: 0
  };
}

function diffSwap(decoded, ethValue) {
  const outEth = parseFloat(ethValue) || 0;
  return {
    lines: [
      diff(ETH, ethValue || "0", "0", "Spent via swap"),
      diff(UNKNOWN_TOKEN, "0", "~?", "Received amount depends on pool and slippage")
    ],
    summary: outEth > 0
      ? `OUT ${ethValue} ETH -> IN tokens (exact amount depends on pool)`
      : `Token swap (exact amounts depend on pool)`,
    totalOutEth: outEth, totalInEth: 0
  };
}

function diffPermit(pd) {
  const unlimited = pd.value === "Unlimited" || /^f{15,}/i.test(pd.value);
  return {
    lines: [diff(pd.tokenName || UNKNOWN_TOKEN, unlimited ? "UNLIMITED" : pd.value, "0",
      `Off-chain signature. No on-chain effect until exploited.`)],
    summary: "No on-chain balance change. Off-chain signature.",
    totalOutEth: 0, totalInEth: 0,
    risk: unlimited ? "unlimited-allowance" : "limited-allowance"
  };
}

function diffBridge() {
  return {
    lines: [diff(UNKNOWN_TOKEN, "Bridged amount", "0", "Tokens will move to another chain.")],
    summary: "Bridge transfer - destination chain must be verified.",
    totalOutEth: 0, totalInEth: 0
  };
}

function diffMulticall(innerDiffs) {
  // innerDiffs: array of { lines, summary, totalOutEth, totalInEth }
  const lines = [];
  let totalOutEth = 0, totalInEth = 0;
  let anyUnlimited = false;
  innerDiffs.forEach((d, i) => {
    if (d.risk === "unlimited-allowance") anyUnlimited = true;
    totalOutEth += d.totalOutEth || 0;
    totalInEth += d.totalInEth || 0;
    d.lines.forEach((l) => lines.push(l));
  });
  return {
    lines,
    summary: `Multicall (${innerDiffs.length} subcalls)`,
    totalOutEth, totalInEth,
    risk: anyUnlimited ? "unlimited-allowance" : undefined
  };
}

// ---------- Top-level entry ----------

// ctx = {
//   to, value, data, ethValue,
//   decoded,
//   isEIP712, isPersonalSign, isLegacySign, permitDetails,
//   innerDiffs: array of diff objects from recursive multicall
// }
function diffTransaction(ctx) {
  const methodId = getMethodId(ctx.data || "");

  if (ctx.isEIP712 && ctx.permitDetails) return diffPermit(ctx.permitDetails);
  if (ctx.isPersonalSign || ctx.isLegacySign) {
    return {
      lines: [diff("Signature", "1", "0", "Off-chain signature. No balance impact until used.")],
      summary: "Off-chain signature. No balance change.",
      totalOutEth: 0, totalInEth: 0
    };
  }

  switch (methodId) {
    case "0x095ea7b3": return diffApprove(ctx.decoded);
    case "0xa22cb465": return diffSetApprovalForAll(ctx.decoded);
    case "0xa9059cbb": return diffTransfer(ctx.decoded, ctx.ethValue);
    case "0x23b872dd": return diffTransferFrom(ctx.decoded);
    case "0x42842e0e":
    case "0xb88d4fde": return diffSafeTransferFrom(ctx.decoded);
    case "0x38ed1739":
    case "0x8803dbee":
    case "0x7ff36ab5":
    case "0x4a25d94a":
    case "0xfb3bdb41":
    case "0x415565b0": return diffSwap(ctx.decoded, ctx.ethValue);
    case "0xac9650d8":
    case "0x5ae401dc":
    case "0x1745e9d0":
    case "0xee8b7563":
      return diffMulticall(ctx.innerDiffs || []);
    case "0x1f0464d1":
    case "0x8b7f1068":
    case "0x301a5c2c": return diffBridge();
  }

  // Unknown method - just surface the ETH value if any.
  const outEth = parseFloat(ctx.ethValue) || 0;
  if (outEth > 0) {
    return {
      lines: [diff(ETH, ctx.ethValue, "0", "Unknown method, native ETH outflow")],
      summary: `OUT ${ctx.ethValue} ETH (unknown method)`,
      totalOutEth: outEth, totalInEth: 0
    };
  }

  return empty();
}

return { diffTransaction };
})();


/* ============================================================
 * lib/revoke-generator.js
 * ============================================================ */
const revoke_generator_js_exports = (function() {
// lib/revoke-generator.js — Generates calldata for revoking active approvals.
//
// The Approval Scanner tells you what's exposed. This module tells you
// exactly what transaction to send to revoke it.
//
// Two kinds of revokes are supported:
//   - ERC-20 approvals:  `approve(spender, 0)`            [selector 0x095ea7b3]
//   - NFT approvals:     `setApprovalForAll(operator, false)` [selector 0xa22cb465]
//
// Both ERC-721 and ERC-1155 use the same setApprovalForAll(address,bool)
// selector, so a single revoke works for both standards.
//
// Why not just sign and broadcast ourselves?
//   Chrome MV3 extensions cannot sign transactions directly. We generate
//   the calldata so the user can:
//     (a) copy it and broadcast via revoke.cash, Pocket Universe, or MEW,
//     (b) hand it to the wallet via EIP-681 / WalletConnect link, or
//     (c) queue it up in a multisend via their wallet's UI.
//
// Every returned "revoke plan" object is self-contained — caller doesn't
// need to know about selectors, padding, or chain-specific behavior.

// ---- Selectors (keccak256 of canonical signatures) ----

// approve(address,uint256)
const ERC20_APPROVE_SELECTOR = "0x095ea7b3";
// setApprovalForAll(address,bool)
const NFT_SET_APPROVAL_FOR_ALL_SELECTOR = "0xa22cb465";

// 32 bytes of zeros — used for `uint256 amount = 0` and `bool = false`.
const ZERO_WORD = "0x" + "0".repeat(64);

/**
 * Pad an address (0x...) to a 32-byte ABI word (left-padded with zeros).
 * @param {string} addr  0x-prefixed 20-byte address
 * @returns {string}     0x-prefixed 32-byte hex
 */
function padAddress(addr) {
  if (typeof addr !== "string") throw new Error("padAddress: expected string");
  const clean = addr.toLowerCase().replace(/^0x/, "");
  if (clean.length !== 40) throw new Error("padAddress: invalid address length: " + addr);
  if (!/^[0-9a-f]{40}$/.test(clean)) throw new Error("padAddress: invalid hex chars: " + addr);
  return "0x" + clean.padStart(64, "0");
}

/**
 * Encode an ERC-20 `approve(spender, 0)` call.
 *
 * @param {string} spender  The address whose allowance should be revoked.
 * @returns {string}        0x-prefixed calldata (selector + 64-byte args)
 */
function buildERC20RevokeCalldata(spender) {
  return ERC20_APPROVE_SELECTOR + padAddress(spender).slice(2) + ZERO_WORD.slice(2);
}

/**
 * Encode an ERC-721 / ERC-1155 `setApprovalForAll(operator, false)` call.
 *
 * @param {string} operator  The operator whose custody should be revoked.
 * @returns {string}         0x-prefixed calldata
 */
function buildNFT721RevokeCalldata(operator) {
  return NFT_SET_APPROVAL_FOR_ALL_SELECTOR + padAddress(operator).slice(2) + ZERO_WORD.slice(2);
}

/**
 * Build a complete "revoke plan" for a single ERC-20 approval object.
 *
 * The `approval` shape matches what approval-scanner.js returns in its
 * `approvals[]` array (see scanERC20Approvals). Pass that object directly
 * — no field extraction needed.
 *
 * @param {object} approval  { token, tokenSymbol, spender, chainId, chainName, ... }
 * @returns {object}         { kind, chainId, chainName, to, data, value, description, ... }
 */
function buildERC20RevokeTx(approval) {
  if (!approval || typeof approval !== "object") {
    throw new Error("buildERC20RevokeTx: approval object required");
  }
  const token = (approval.token || "").toLowerCase();
  const spender = (approval.spender || "").toLowerCase();
  if (!/^0x[a-f0-9]{40}$/.test(token)) {
    throw new Error("buildERC20RevokeTx: invalid token address: " + approval.token);
  }
  if (!/^0x[a-f0-9]{40}$/.test(spender)) {
    throw new Error("buildERC20RevokeTx: invalid spender address: " + approval.spender);
  }
  return {
    kind: "ERC-20",
    chainId: approval.chainId,
    chainName: approval.chainName || ("Chain " + approval.chainId),
    to: token,
    data: buildERC20RevokeCalldata(spender),
    value: "0x0",
    description: describeRevoke(approval, "ERC-20"),
    token: token,
    tokenSymbol: approval.tokenSymbol || shorten(token),
    spender: spender,
    spenderName: approval.spenderName || null,
    isUnlimited: !!approval.isUnlimited,
    allowanceFmt: approval.allowanceFmt || null
  };
}

/**
 * Build a complete revoke plan for a single NFT approval object.
 *
 * @param {object} nftApproval  { collection, collectionName, operator, operatorName, chainId, chainName, ... }
 * @returns {object}            Same shape as buildERC20RevokeTx
 */
function buildNFT721RevokeTx(nftApproval) {
  if (!nftApproval || typeof nftApproval !== "object") {
    throw new Error("buildNFT721RevokeTx: approval object required");
  }
  const collection = (nftApproval.collection || "").toLowerCase();
  const operator = (nftApproval.operator || "").toLowerCase();
  if (!/^0x[a-f0-9]{40}$/.test(collection)) {
    throw new Error("buildNFT721RevokeTx: invalid collection address: " + nftApproval.collection);
  }
  if (!/^0x[a-f0-9]{40}$/.test(operator)) {
    throw new Error("buildNFT721RevokeTx: invalid operator address: " + nftApproval.operator);
  }
  return {
    kind: "NFT",
    chainId: nftApproval.chainId,
    chainName: nftApproval.chainName || ("Chain " + nftApproval.chainId),
    to: collection,
    data: buildNFT721RevokeCalldata(operator),
    value: "0x0",
    description: describeRevoke(nftApproval, "NFT"),
    token: collection,
    tokenSymbol: nftApproval.collectionName || shorten(collection),
    spender: operator,
    spenderName: nftApproval.operatorName || null,
    isUnlimited: true,
    allowanceFmt: "Full custody"
  };
}

/**
 * Auto-detect approval type and build the appropriate revoke plan.
 * Returns null if the approval kind cannot be determined.
 *
 * @param {object} approval  Either an ERC-20 or NFT approval object
 * @returns {object|null}    Revoke plan from buildERC20RevokeTx / buildNFT721RevokeTx
 */
function buildRevokeTx(approval) {
  if (!approval || typeof approval !== "object") return null;
  const type = (approval.tokenType || "").toUpperCase();
  if (type === "ERC-721" || type === "ERC-1155" || approval.collection) {
    return buildNFT721RevokeTx(approval);
  }
  // Default: ERC-20
  if (approval.token && approval.spender) {
    return buildERC20RevokeTx(approval);
  }
  return null;
}

/**
 * Build a batch of revoke plans for an array of approvals (mixed kinds).
 * Skips entries that fail validation but reports them in `errors[]`.
 *
 * @param {Array<object>} approvals
 * @returns {{ plans: object[], errors: Array<{approval, reason}> }}
 */
function buildRevokeBatch(approvals) {
  const plans = [];
  const errors = [];
  if (!Array.isArray(approvals)) return { plans, errors };
  for (const a of approvals) {
    try {
      const plan = buildRevokeTx(a);
      if (plan) plans.push(plan);
      else errors.push({ approval: a, reason: "unknown approval kind" });
    } catch (e) {
      errors.push({ approval: a, reason: e.message || String(e) });
    }
  }
  return { plans, errors };
}

/**
 * Group a list of revoke plans by chainId so the UI can show a separate
 * "Sign N transactions on Ethereum, M on Polygon" summary.
 *
 * @param {Array<object>} plans
 * @returns {Array<{chainId, chainName, plans, count}>}
 */
function groupPlansByChain(plans) {
  const byChain = new Map();
  for (const p of (plans || [])) {
    if (!byChain.has(p.chainId)) {
      byChain.set(p.chainId, { chainId: p.chainId, chainName: p.chainName || ("Chain " + p.chainId), plans: [], count: 0 });
    }
    const g = byChain.get(p.chainId);
    g.plans.push(p);
    g.count++;
  }
  return Array.from(byChain.values()).sort((a, b) => a.chainId - b.chainId);
}

// ---- Internal helpers ----

function shorten(addr) {
  if (!addr || addr.length < 12) return addr || "";
  return addr.slice(0, 6) + "..." + addr.slice(-4);
}

function describeRevoke(a, kind) {
  if (kind === "NFT") {
    const op = a.operatorName || shorten((a.operator || "").toLowerCase());
    const coll = a.collectionName || shorten((a.collection || "").toLowerCase());
    return `Revoke NFT custody: ${coll} → ${op}`;
  }
  const sym = a.tokenSymbol || "Token";
  const sp = a.spenderName || shorten((a.spender || "").toLowerCase());
  return `Revoke ${sym} approval → ${sp}`;
}

return { padAddress, buildERC20RevokeCalldata, buildNFT721RevokeCalldata, buildERC20RevokeTx, buildNFT721RevokeTx, buildRevokeTx, buildRevokeBatch, groupPlansByChain, ERC20_APPROVE_SELECTOR, NFT_SET_APPROVAL_FOR_ALL_SELECTOR, ZERO_WORD };
})();


// ============================================================
// BINDINGS - alias exports to their original names
// ============================================================
const TRUSTED_DOMAINS = constants_js_exports.TRUSTED_DOMAINS;
const SEED_BLACKLIST = constants_js_exports.SEED_BLACKLIST;
const KNOWN_SAFE_CONTRACTS = constants_js_exports.KNOWN_SAFE_CONTRACTS;
const UR_COMMANDS = constants_js_exports.UR_COMMANDS;
const MAX_DECODE_DEPTH = constants_js_exports.MAX_DECODE_DEPTH;
const strip0x = decoder_js_exports.strip0x;
const sliceAddress = decoder_js_exports.sliceAddress;
const sliceUint256 = decoder_js_exports.sliceUint256;
const sliceBool = decoder_js_exports.sliceBool;
const shortAddr = decoder_js_exports.shortAddr;
const formatTokenAmount = decoder_js_exports.formatTokenAmount;
const weiToEth = decoder_js_exports.weiToEth;
const getMethodId = decoder_js_exports.getMethodId;
const decodeCalldata = decoder_js_exports.decodeCalldata;
const METHOD_DECODER = decoder_js_exports.METHOD_DECODER;
const levenshtein = typosquatting_js_exports.levenshtein;
const getRegistrableDomain = typosquatting_js_exports.getRegistrableDomain;
const findTyposquatting = typosquatting_js_exports.findTyposquatting;
const isMulticall = multicall_decoder_js_exports.isMulticall;
const extractInnerCalls = multicall_decoder_js_exports.extractInnerCalls;
const isUniversalRouter = universal_router_js_exports.isUniversalRouter;
const decodeUniversalRouter = universal_router_js_exports.decodeUniversalRouter;
const computeRisk = risk_engine_js_exports.computeRisk;
const describeCapabilities = capabilities_js_exports.describeCapabilities;
const diffTransaction = simulator_js_exports.diffTransaction;
const padAddress = revoke_generator_js_exports.padAddress;
const buildERC20RevokeCalldata = revoke_generator_js_exports.buildERC20RevokeCalldata;
const buildNFT721RevokeCalldata = revoke_generator_js_exports.buildNFT721RevokeCalldata;
const buildERC20RevokeTx = revoke_generator_js_exports.buildERC20RevokeTx;
const buildNFT721RevokeTx = revoke_generator_js_exports.buildNFT721RevokeTx;
const buildRevokeTx = revoke_generator_js_exports.buildRevokeTx;
const buildRevokeBatch = revoke_generator_js_exports.buildRevokeBatch;
const groupPlansByChain = revoke_generator_js_exports.groupPlansByChain;
const ERC20_APPROVE_SELECTOR = revoke_generator_js_exports.ERC20_APPROVE_SELECTOR;
const NFT_SET_APPROVAL_FOR_ALL_SELECTOR = revoke_generator_js_exports.NFT_SET_APPROVAL_FOR_ALL_SELECTOR;
const ZERO_WORD = revoke_generator_js_exports.ZERO_WORD;


// ============================================================
// ORCHESTRATOR (was content.js)
// ============================================================






















// content.js - WalletGuard Pro Orchestrator (ISOLATED world)
//
// Runs in every page at document_start. Responsibilities:
//   1. Listen for `WalletGuardShowUI` events from injector.js (MAIN world).
//   2. Analyze the payload: decode calldata, recursively decode multicall/UR,
//      compute risk score, generate asset diff and capability explanations.
//   3. Show a full-screen overlay with the analysis.
//   4. On user choice, dispatch `WalletGuardUIResponse` so the injector
//      either passes the call through or throws (rejected).
//   5. Listen for `WalletGuardTestPhishing` (from test.html) to demo phishing overlay.
//   6. Send stats to the background service worker.

(function () {
  "use strict";

  console.log("WalletGuard Pro: content script active.");

  // ============================================================
  // BACKGROUND HELPERS
  // ============================================================

  function sendBg(msg) {
    try {
      chrome.runtime.sendMessage(msg, () => {
        // swallow "receiving end does not exist" errors
        void chrome.runtime.lastError;
      });
    } catch (e) { /* ignore */ }
  }

  function getBg(msg) {
    return new Promise((resolve) => {
      try {
        chrome.runtime.sendMessage(msg, (response) => {
          if (chrome.runtime.lastError) return resolve(null);
          resolve(response || null);
        });
      } catch (e) {
        resolve(null);
      }
    });
  }

  // ============================================================
  // SITE TRACKING
  // ============================================================

  (async function trackSite() {
    const host = location.hostname.replace(/^www\./, "");
    if (!host) return;
    try {
      const session = sessionStorage.getItem("wg_seen") || "";
      if (session.split(",").includes(host)) return;
      sessionStorage.setItem("wg_seen", session + "," + host);
    } catch { /* ignore */ }
    sendBg({ action: "siteAnalyzed", host });
  })();

  // ============================================================
  // ANALYSIS PIPELINE
  // ============================================================

  async function analyze(payload) {
    const target = (payload.to || "").toLowerCase();
    const data = payload.data || "0x";
    const valueHex = payload.value || "0x0";
    const methodId = getMethodId(data);

    let ethValue = payload.ethAmount || "0";
    let ethFloat = parseFloat(ethValue) || 0;
    if (!payload.ethAmount) {
      try {
        const wei = BigInt(valueHex);
        const whole = wei / 10n ** 18n;
        const frac = wei % 10n ** 18n;
        const fracStr = frac.toString().padStart(18, "0").slice(0, 6);
        ethValue = ("" + whole + "." + fracStr).replace(/\.?0+$/, "") || "0";
        ethFloat = parseFloat(ethValue) || 0;
      } catch { /* keep defaults */ }
    }

    const settings = await getBg({ action: "getSettings" });
    const whitelist = new Set(
      (settings?.whitelist || [])
        .filter((x) => typeof x === "string" && /^0x[a-fA-F0-9]{40}$/.test(x))
        .map((x) => x.toLowerCase())
    );

    const decoded = methodId ? decodeCalldata(methodId, data) : null;
    const unknownMethod = !!methodId && !decoded && !isMulticall(methodId) && !isUniversalRouter(methodId);

    let innerCalls = [];
    let innerFactors = [];
    let innerDiffs = [];
    if (methodId && isMulticall(methodId)) {
      innerCalls = extractInnerCalls(methodId, data);
      for (const c of innerCalls) {
        const subMethodId = getMethodId(c.data || "");
        const subDecoded = subMethodId ? decodeCalldata(subMethodId, c.data) : null;
        const subCtx = {
          target: c.target,
          from: payload.from,
          value: "0x0",
          data: c.data,
          ethValue: "0",
          ethFloat: 0,
          decoded: subDecoded,
          unknownMethod: !!subMethodId && !subDecoded && !isMulticall(subMethodId),
          trustedAddresses: whitelist
        };
        innerFactors.push(computeRisk(subCtx));
        innerDiffs.push(diffTransaction({ data: c.data, ethValue: "0", decoded: subDecoded }));
      }
    }

    let urCommands = null;
    if (methodId && isUniversalRouter(methodId)) {
      const ur = decodeUniversalRouter(data);
      if (ur) urCommands = ur.commands;
    }

    const hostname = (payload.hostname || location.hostname || "").replace(/^www\./, "").toLowerCase();

    const ctx = {
      target,
      from: payload.from,
      value: valueHex,
      data,
      ethValue,
      ethFloat,
      decoded,
      unknownMethod,
      innerCalls,
      innerFactors,
      urCommands,
      isEIP712: !!payload.isEIP712,
      isPersonalSign: !!payload.isPersonalSign,
      isLegacySign: !!payload.isLegacySign,
      permitDetails: payload.permitDetails,
      trustedAddresses: whitelist,
      hostname
    };

    const risk = computeRisk(ctx);
    const diff = diffTransaction({ ...ctx, innerDiffs });
    const capabilities = describeCapabilities({ ...ctx, innerDiffs });

    return {
      method: payload.method,
      target,
      from: payload.from,
      value: valueHex,
      ethValue,
      data,
      methodInfo: methodId ? METHOD_DECODER[methodId] : null,
      risk,
      diff,
      capabilities,
      innerCalls,
      urCommands,
      permitDetails: payload.permitDetails,
      messageText: payload.messageText,
      hostname
    };
  }

  // ============================================================
  // UI RENDERING
  // ============================================================

  let overlayEl = null;

  function removeOverlay() {
    if (overlayEl && overlayEl.parentNode) overlayEl.parentNode.removeChild(overlayEl);
    overlayEl = null;
    document.documentElement.style.overflow = "";
  }

  function showOverlay(analysis) {
    removeOverlay();
    document.documentElement.style.overflow = "hidden";

    overlayEl = document.createElement("div");
    overlayEl.id = "wg-overlay-root";
    overlayEl.innerHTML = renderOverlay(analysis);
    document.body.appendChild(overlayEl);

    overlayEl.querySelector("[data-action=approve]").addEventListener("click", () => {
      sendBg({ action: "warningShown" });
      window.dispatchEvent(new CustomEvent("WalletGuardUIResponse", { detail: { approved: true } }));
      removeOverlay();
    });
    overlayEl.querySelector("[data-action=reject]").addEventListener("click", () => {
      sendBg({ action: "txBlocked", target: analysis.target });
      window.dispatchEvent(new CustomEvent("WalletGuardUIResponse", { detail: { approved: false } }));
      removeOverlay();
    });
    overlayEl.querySelector("[data-action=close]").addEventListener("click", removeOverlay);
  }

  function renderOverlay(a) {
    const r = a.risk || {};
    const factors = r.factors || [];
    const diff = a.diff || {};
    const lines = diff.lines || [];
    const innerCalls = a.innerCalls || [];
    const urCommands = a.urCommands || [];
    const methodLabel = a.methodInfo
      ? `${a.methodInfo.category} - ${a.methodInfo.name}`
      : (a.data === "0x" || !a.data)
        ? "Native ETH Transfer"
        : "Unknown Method";

    const factorsHtml = factors.map((f) => {
      const cls = f.severity === "critical" || f.severity === "high"
        ? "wg-factor-bad"
        : f.severity === "medium"
          ? "wg-factor-warn"
          : f.severity === "positive"
            ? "wg-factor-good"
            : "wg-factor-info";
      const sign = f.weight >= 0 ? "+" : "";
      return `<div class="wg-factor ${cls}">
        <span class="wg-factor-name">${escapeHtml(f.name)}</span>
        <span class="wg-factor-weight">${sign}${f.weight}</span>
        <div class="wg-factor-desc">${escapeHtml(f.description)}</div>
      </div>`;
    }).join("");

    const linesHtml = lines.map((l) => `
      <div class="wg-diff-row">
        <span class="wg-diff-symbol">${escapeHtml(l.symbol)}</span>
        <span class="wg-diff-out">${escapeHtml(l.sent)}</span>
        <span class="wg-diff-arrow">&rarr;</span>
        <span class="wg-diff-in">${escapeHtml(l.received)}</span>
        ${l.note ? `<span class="wg-diff-note">${escapeHtml(l.note)}</span>` : ""}
      </div>
    `).join("");

    const innerHtml = innerCalls.length ? `
      <div class="wg-section">
        <div class="wg-section-title">Multicall Subcalls (${innerCalls.length})</div>
        <ol class="wg-inner-list">
          ${innerCalls.map((c) => {
            const m = c.data ? METHOD_DECODER[getMethodId(c.data)] : null;
            const t = c.target ? shortAddr(c.target) : "?";
            const name = m ? m.name : "Unknown";
            return `<li><span class="wg-inner-target">${escapeHtml(t)}</span> &middot; ${escapeHtml(name)}</li>`;
          }).join("")}
        </ol>
      </div>
    ` : "";

    const urHtml = urCommands && urCommands.length ? `
      <div class="wg-section">
        <div class="wg-section-title">Universal Router Commands (${urCommands.length})</div>
        <ol class="wg-ur-list">
          ${urCommands.map((c) => `
            <li>
              <span class="wg-ur-byte">0x${c.byte.toString(16).padStart(2, "0")}</span>
              <span class="wg-ur-name">${escapeHtml(c.name)}</span>
              <span class="wg-ur-risk wg-risk-${escapeHtml(c.risk.toLowerCase())}">${escapeHtml(c.risk)}</span>
              <div class="wg-ur-desc">${escapeHtml(c.desc)}</div>
            </li>
          `).join("")}
        </ol>
      </div>
    ` : "";

    const messageHtml = a.messageText ? `
      <div class="wg-section">
        <div class="wg-section-title">Signed Message</div>
        <pre class="wg-message">${escapeHtml(a.messageText)}</pre>
      </div>
    ` : "";

    const permitHtml = a.permitDetails ? `
      <div class="wg-section">
        <div class="wg-section-title">Permit Details</div>
        <div class="wg-permit">
          <div><b>Token:</b> ${escapeHtml(a.permitDetails.tokenName || "?")}</div>
          <div><b>Spender:</b> ${escapeHtml(a.permitDetails.spender || "?")}</div>
          <div><b>Value:</b> ${escapeHtml(a.permitDetails.value || "?")}</div>
          ${a.permitDetails.deadline ? `<div><b>Valid until:</b> ${escapeHtml(a.permitDetails.deadline)}</div>` : ""}
        </div>
      </div>
    ` : "";

    const dv = r.domainVerdict;
    let domainBanner = "";
    if (dv && dv.type !== "trusted") {
      const headlines = {
        "typosquat": "POSSIBLE TYPOSQUATTING",
        "subdomain-attack": "PHISHING — SUBDOMAIN IMPERSONATION",
        "homoglyph": "PHISHING — LOOK-ALIKE DOMAIN"
      };
      const explanations = {
        "typosquat": `${a.hostname} is ${dv.distance} character${dv.distance === 1 ? "" : "s"} away from the real ${dv.match}. Did you mistype the URL?`,
        "subdomain-attack": `The string "${dv.match}" appears in the hostname, but this site's real domain is "${dv.hostname}". This is the #1 phishing pattern in Web3.`,
        "homoglyph": dv.match
          ? `${a.hostname} uses characters that look identical to ${dv.match} but are actually different (homoglyph attack).`
          : `${a.hostname} contains non-ASCII characters that may mimic a trusted site. Verify carefully.`
      };
      domainBanner = `
    <div class="wg-domain-warn">
      <div class="wg-domain-warn-title">${headlines[dv.type] || "PHISHING"}</div>
      <div class="wg-domain-warn-body">${escapeHtml(explanations[dv.type] || "")}</div>
      ${dv.match ? `<div class="wg-domain-warn-true">Real site: <span class="mono">${escapeHtml(dv.match)}</span></div>` : ""}
    </div>`;
    } else if (dv && dv.type === "trusted") {
      domainBanner = `
    <div class="wg-domain-trust">Trusted site &middot; ${escapeHtml(dv.match)}</div>`;
    }

    return `
<style>${OVERLAY_CSS}</style>
<div class="wg-backdrop">
  <div class="wg-modal">
    ${domainBanner}
    <div class="wg-header" style="border-left: 6px solid ${r.accentColor || "#00ffcc"};">
      <div class="wg-header-left">
        <div class="wg-logo">WG</div>
        <div>
          <div class="wg-title">${escapeHtml(r.riskLevel || "WalletGuard")}</div>
          <div class="wg-subtitle">${escapeHtml(methodLabel)}</div>
        </div>
      </div>
      <div class="wg-score">
        <div class="wg-score-num">${r.trustScore ?? "--"}</div>
        <div class="wg-score-den">/100</div>
      </div>
      <button class="wg-close" data-action="close" title="Dismiss">&times;</button>
    </div>

    <div class="wg-section">
      <div class="wg-section-title">Transaction</div>
      <div class="wg-tx">
        <div><span class="wg-label">To:</span> <span class="mono">${escapeHtml(shortAddr(a.target) || "?")}</span></div>
        <div><span class="wg-label">From:</span> <span class="mono">${escapeHtml(shortAddr(a.from) || "?")}</span></div>
        <div><span class="wg-label">Value:</span> <span class="mono">${escapeHtml(a.ethValue || "0")} ETH</span></div>
      </div>
    </div>

    ${linesHtml ? `<div class="wg-section"><div class="wg-section-title">Asset Changes</div><div class="wg-diff">${linesHtml}</div></div>` : ""}

    <div class="wg-section">
      <div class="wg-section-title">Risk Factors</div>
      <div class="wg-factors">${factorsHtml || '<div class="wg-factor wg-factor-info"><span class="wg-factor-name">No specific risks flagged</span></div>'}</div>
    </div>

    ${permitHtml}
    ${messageHtml}
    ${innerHtml}
    ${urHtml}

    <div class="wg-section">
      <div class="wg-section-title">What this lets the contract do</div>
      <ul class="wg-caps">${(a.capabilities || []).map((c) => `<li>${escapeHtml(c)}</li>`).join("")}</ul>
    </div>

    <div class="wg-footer">
      <button class="wg-btn wg-btn-danger" data-action="reject">Reject</button>
      <button class="wg-btn wg-btn-primary" data-action="approve">Approve anyway</button>
    </div>
  </div>
</div>
`;
  }

  const OVERLAY_CSS = `
#wg-overlay-root { all: initial; }
#wg-overlay-root, #wg-overlay-root * { box-sizing: border-box; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; }
.wg-backdrop { position: fixed; inset: 0; background: rgba(5, 7, 12, 0.85); backdrop-filter: blur(8px); z-index: 2147483647; display: flex; align-items: center; justify-content: center; padding: 24px; overflow-y: auto; }
.wg-modal { background: #12151d; color: #fff; border: 1px solid rgba(255,255,255,0.06); border-radius: 16px; width: 100%; max-width: 560px; box-shadow: 0 20px 60px rgba(0,0,0,0.5); overflow: hidden; }
.wg-header { display: flex; align-items: center; gap: 12px; padding: 16px 18px; background: rgba(255,255,255,0.02); }
.wg-header-left { display: flex; align-items: center; gap: 12px; flex: 1; }
.wg-logo { width: 36px; height: 36px; background: #00ffcc; color: #0a0c12; border-radius: 8px; display: flex; align-items: center; justify-content: center; font-weight: 800; font-size: 14px; }
.wg-title { font-size: 15px; font-weight: 800; letter-spacing: 0.5px; }
.wg-subtitle { font-size: 11px; color: #8a92a3; margin-top: 2px; }
.wg-score { display: flex; align-items: baseline; gap: 2px; }
.wg-score-num { font-size: 32px; font-weight: 800; }
.wg-score-den { font-size: 14px; color: #4c5264; font-weight: 600; }
.wg-close { background: transparent; border: none; color: #8a92a3; font-size: 22px; cursor: pointer; padding: 0 6px; line-height: 1; }
.wg-close:hover { color: #fff; }
.wg-section { padding: 14px 18px; border-bottom: 1px solid rgba(255,255,255,0.04); }
.wg-section:last-of-type { border-bottom: none; }
.wg-section-title { font-size: 10px; font-weight: 700; color: #646b7c; letter-spacing: 1px; text-transform: uppercase; margin-bottom: 8px; }
.wg-tx { font-size: 12px; line-height: 1.7; color: rgba(255,255,255,0.85); }
.wg-label { color: #646b7c; font-size: 11px; font-weight: 600; display: inline-block; min-width: 50px; }
.mono { font-family: 'SF Mono', Menlo, monospace; }
.wg-diff-row { display: grid; grid-template-columns: 60px 1fr 16px 1fr; gap: 8px; align-items: center; font-size: 12px; padding: 4px 0; }
.wg-diff-symbol { font-weight: 700; }
.wg-diff-out { color: #ff6b6b; font-family: 'SF Mono', Menlo, monospace; font-size: 11px; }
.wg-diff-arrow { color: #4c5264; text-align: center; }
.wg-diff-in { color: #00ff66; font-family: 'SF Mono', Menlo, monospace; font-size: 11px; }
.wg-diff-note { grid-column: 1 / -1; font-size: 10px; color: #4c5264; padding-left: 68px; }
.wg-factors { display: flex; flex-direction: column; gap: 6px; }
.wg-factor { padding: 8px 10px; border-radius: 8px; background: rgba(255,255,255,0.03); border-left: 3px solid #646b7c; display: grid; grid-template-columns: 1fr auto; gap: 4px; }
.wg-factor-name { font-size: 12px; font-weight: 700; }
.wg-factor-weight { font-size: 12px; font-weight: 700; font-family: 'SF Mono', Menlo, monospace; }
.wg-factor-desc { grid-column: 1 / -1; font-size: 11px; color: #8a92a3; line-height: 1.4; margin-top: 2px; }
.wg-factor-bad { border-left-color: #ff4d4d; }
.wg-factor-bad .wg-factor-weight { color: #ff4d4d; }
.wg-factor-warn { border-left-color: #ffb700; }
.wg-factor-warn .wg-factor-weight { color: #ffb700; }
.wg-factor-good { border-left-color: #00ff66; }
.wg-factor-good .wg-factor-weight { color: #00ff66; }
.wg-factor-info { border-left-color: #00ffcc; }
.wg-factor-info .wg-factor-weight { color: #00ffcc; }
.wg-inner-list, .wg-ur-list { margin: 0; padding-left: 20px; font-size: 12px; line-height: 1.7; }
.wg-inner-target, .wg-ur-byte { font-family: 'SF Mono', Menlo, monospace; color: #00ffcc; font-size: 11px; }
.wg-ur-name { font-weight: 700; }
.wg-ur-risk { font-size: 10px; padding: 1px 6px; border-radius: 4px; margin-left: 6px; font-weight: 700; letter-spacing: 0.3px; }
.wg-risk-critical { background: rgba(255,51,51,0.15); color: #ff3333; }
.wg-risk-high { background: rgba(255,107,107,0.15); color: #ff6b6b; }
.wg-risk-medium { background: rgba(255,183,0,0.15); color: #ffb700; }
.wg-risk-low { background: rgba(0,255,102,0.15); color: #00ff66; }
.wg-risk-info { background: rgba(0,255,204,0.15); color: #00ffcc; }
.wg-ur-desc { font-size: 10px; color: #8a92a3; margin-top: 2px; }
.wg-message { background: rgba(0,0,0,0.3); border: 1px solid rgba(255,255,255,0.05); border-radius: 6px; padding: 8px; font-size: 11px; font-family: 'SF Mono', Menlo, monospace; color: rgba(255,255,255,0.8); white-space: pre-wrap; word-break: break-word; max-height: 120px; overflow-y: auto; }
.wg-permit { font-size: 12px; line-height: 1.7; }
.wg-caps { margin: 0; padding-left: 20px; font-size: 12px; line-height: 1.6; color: rgba(255,255,255,0.85); }
.wg-caps li { margin-bottom: 4px; }
.wg-footer { display: flex; gap: 10px; padding: 16px 18px; background: rgba(0,0,0,0.2); }
.wg-btn { flex: 1; padding: 12px 16px; border-radius: 10px; border: 1px solid transparent; font-size: 13px; font-weight: 700; cursor: pointer; font-family: inherit; transition: all 0.2s; }
.wg-btn-primary { background: #00ffcc; color: #0a0c12; }
.wg-btn-primary:hover { background: #00e6b8; }
.wg-btn-danger { background: rgba(255,77,77,0.1); color: #ff6b6b; border-color: rgba(255,77,77,0.3); }
.wg-btn-danger:hover { background: rgba(255,77,77,0.18); }
.wg-domain-warn { padding: 14px 18px; background: linear-gradient(135deg, rgba(255,51,51,0.25), rgba(180,0,0,0.35)); border-bottom: 2px solid #ff3333; }
.wg-domain-warn-title { font-size: 12px; font-weight: 800; color: #ff3333; letter-spacing: 1px; margin-bottom: 6px; }
.wg-domain-warn-body { font-size: 12px; line-height: 1.5; color: #fff; margin-bottom: 6px; }
.wg-domain-warn-true { font-size: 11px; color: rgba(255,255,255,0.75); padding-top: 6px; border-top: 1px solid rgba(255,255,255,0.15); }
.wg-domain-warn-true .mono { color: #00ffcc; font-weight: 700; }
.wg-domain-trust { padding: 10px 18px; background: rgba(0,255,102,0.08); border-bottom: 1px solid rgba(0,255,102,0.3); font-size: 11px; color: #00ff66; font-weight: 700; letter-spacing: 0.5px; }
`;

  // ============================================================
  // PHISHING OVERLAY
  // ============================================================

  function showPhishing(domain) {
    if (overlayEl) removeOverlay();
    document.documentElement.style.overflow = "hidden";

    overlayEl = document.createElement("div");
    overlayEl.id = "wg-overlay-root";
    overlayEl.innerHTML = `
<style>${OVERLAY_CSS}</style>
<div class="wg-backdrop" style="background: rgba(50,0,0,0.95);">
  <div class="wg-modal" style="border: 2px solid #ff3333;">
    <div class="wg-header" style="border-left: 6px solid #ff3333; background: rgba(255,51,51,0.08);">
      <div class="wg-header-left">
        <div class="wg-logo" style="background: #ff3333; color: #fff;">!</div>
        <div>
          <div class="wg-title" style="color: #ff3333;">PHISHING BLOCKED</div>
          <div class="wg-subtitle">${escapeHtml(domain || location.hostname)}</div>
        </div>
      </div>
      <button class="wg-close" data-action="close">&times;</button>
    </div>
    <div class="wg-section">
      <p style="margin: 0 0 12px 0; font-size: 13px; line-height: 1.5;">This domain has been flagged as malicious or is not in your trusted list. WalletGuard will not transmit any transactions or signatures to this page.</p>
      <p style="margin: 0; font-size: 11px; color: #8a92a3;">If you believe this is a false positive, you can close this overlay and proceed - but verify the URL carefully first.</p>
    </div>
    <div class="wg-footer">
      <button class="wg-btn wg-btn-primary" data-action="close">Close</button>
    </div>
  </div>
</div>
`;
    document.body.appendChild(overlayEl);
    overlayEl.querySelector("[data-action=close]").addEventListener("click", removeOverlay);
    sendBg({ action: "phishingBlocked", domain: domain || location.hostname });
  }

  // ============================================================
  // EVENT WIRING
  // ============================================================

  window.addEventListener("WalletGuardShowUI", async (e) => {
    const payload = e.detail || {};
    try {
      const analysis = await analyze(payload);
      showOverlay(analysis);
      sendBg({ action: "txIntercepted", method: payload.method, from: payload.from });
      if (payload.isEIP712 && payload.permitDetails) {
        sendBg({ action: "permitDetected", spender: payload.permitDetails.spenderFull || payload.permitDetails.spender });
      }
    } catch (err) {
      console.error("WalletGuard: analysis failed:", err);
      window.dispatchEvent(new CustomEvent("WalletGuardUIResponse", { detail: { approved: true } }));
    }
  });

  window.addEventListener("WalletGuardTestPhishing", (e) => {
    const domain = (e.detail && e.detail.domain) || location.hostname;
    showPhishing(domain);
  });

  // ============================================================
  // RPC BRIDGE: SW -> content -> MAIN-world provider
  //
  // The service worker can't dispatch events on the page directly.
  // It sends us a `wgRpcCall` message via chrome.tabs.sendMessage.
  // We forward it to the MAIN-world injector (which has access to
  // the un-wrapped window.ethereum.request), wait for the response,
  // and post it back to the SW.
  // ============================================================

  const rpcPending = new Map();

  window.addEventListener("WalletGuardRpcResponse", (e) => {
    const detail = e && e.detail;
    if (!detail || !detail.id) return;
    const pending = rpcPending.get(detail.id);
    if (!pending) return;
    rpcPending.delete(detail.id);
    clearTimeout(pending.timer);
    if (detail.error) pending.reject(new Error(detail.error));
    else pending.resolve(detail.result);
  });

  chrome.runtime.onMessage.addListener((msg, sender, sendResponse) => {
    if (!msg || msg.action !== "wgRpcCall") return;
    const id = msg.id;
    if (!id) { sendResponse({ error: "missing id" }); return true; }

    // Forward to MAIN world via window event.
    window.dispatchEvent(new CustomEvent("WalletGuardRpcCall", {
      detail: { id: id, method: msg.method, params: msg.params || [] }
    }));

    // Race against a timeout - the MAIN-world listener should reply
    // via WalletGuardRpcResponse; we relay it back to the SW.
    const timer = setTimeout(() => {
      if (rpcPending.has(id)) {
        rpcPending.delete(id);
        sendResponse({ id: id, error: "timeout: " + (msg.method || "rpc") });
      }
    }, 15000);

    rpcPending.set(id, {
      timer: timer,
      resolve: (result) => sendResponse({ id: id, result: result }),
      reject: (err)   => sendResponse({ id: id, error: err.message || String(err) })
    });
    return true; // keep channel open for async response
  });

  // ============================================================
  // UTILITIES
  // ============================================================

  function escapeHtml(str) {
    return String(str == null ? "" : str)
      .replace(/&/g, "&amp;")
      .replace(/</g, "&lt;")
      .replace(/>/g, "&gt;")
      .replace(/"/g, "&quot;")
      .replace(/'/g, "&#39;");
  }

})();























